// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module kernel_pr_entry_proc (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        H_write0,
        H_write0_c_din,
        H_write0_c_full_n,
        H_write0_c_write,
        H_write1,
        H_write1_c_din,
        H_write1_c_full_n,
        H_write1_c_write,
        H_write2,
        H_write2_c_din,
        H_write2_c_full_n,
        H_write2_c_write,
        H_write3,
        H_write3_c_din,
        H_write3_c_full_n,
        H_write3_c_write,
        H_write4,
        H_write4_c_din,
        H_write4_c_full_n,
        H_write4_c_write,
        H_write5,
        H_write5_c_din,
        H_write5_c_full_n,
        H_write5_c_write,
        H_write6,
        H_write6_c_din,
        H_write6_c_full_n,
        H_write6_c_write,
        H_write7,
        H_write7_c_din,
        H_write7_c_full_n,
        H_write7_c_write,
        H_write8,
        H_write8_c_din,
        H_write8_c_full_n,
        H_write8_c_write,
        H_write9,
        H_write9_c_din,
        H_write9_c_full_n,
        H_write9_c_write,
        H_write10,
        H_write10_c_din,
        H_write10_c_full_n,
        H_write10_c_write,
        H_write11,
        H_write11_c_din,
        H_write11_c_full_n,
        H_write11_c_write,
        H_write12,
        H_write12_c_din,
        H_write12_c_full_n,
        H_write12_c_write,
        H_write13,
        H_write13_c_din,
        H_write13_c_full_n,
        H_write13_c_write,
        H_write14,
        H_write14_c_din,
        H_write14_c_full_n,
        H_write14_c_write,
        H_write15,
        H_write15_c_din,
        H_write15_c_full_n,
        H_write15_c_write,
        hyperedge_size,
        hyperedge_size_c_din,
        hyperedge_size_c_full_n,
        hyperedge_size_c_write,
        hyperedge_size_c71_din,
        hyperedge_size_c71_full_n,
        hyperedge_size_c71_write,
        hyperedge_size_c72_din,
        hyperedge_size_c72_full_n,
        hyperedge_size_c72_write,
        hyperedge_size_c73_din,
        hyperedge_size_c73_full_n,
        hyperedge_size_c73_write,
        hyperedge_size_c74_din,
        hyperedge_size_c74_full_n,
        hyperedge_size_c74_write,
        hyperedge_size_c75_din,
        hyperedge_size_c75_full_n,
        hyperedge_size_c75_write,
        hyperedge_size_c76_din,
        hyperedge_size_c76_full_n,
        hyperedge_size_c76_write,
        hyperedge_size_c77_din,
        hyperedge_size_c77_full_n,
        hyperedge_size_c77_write,
        hyperedge_size_c78_din,
        hyperedge_size_c78_full_n,
        hyperedge_size_c78_write,
        hyperedge_size_c79_din,
        hyperedge_size_c79_full_n,
        hyperedge_size_c79_write,
        hyperedge_size_c80_din,
        hyperedge_size_c80_full_n,
        hyperedge_size_c80_write,
        hyperedge_size_c81_din,
        hyperedge_size_c81_full_n,
        hyperedge_size_c81_write,
        hyperedge_size_c82_din,
        hyperedge_size_c82_full_n,
        hyperedge_size_c82_write,
        hyperedge_size_c83_din,
        hyperedge_size_c83_full_n,
        hyperedge_size_c83_write,
        hyperedge_size_c84_din,
        hyperedge_size_c84_full_n,
        hyperedge_size_c84_write,
        hyperedge_size_c85_din,
        hyperedge_size_c85_full_n,
        hyperedge_size_c85_write,
        ap_ext_blocking_n,
        ap_str_blocking_n,
        ap_int_blocking_n
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [63:0] H_write0;
output  [63:0] H_write0_c_din;
input   H_write0_c_full_n;
output   H_write0_c_write;
input  [63:0] H_write1;
output  [63:0] H_write1_c_din;
input   H_write1_c_full_n;
output   H_write1_c_write;
input  [63:0] H_write2;
output  [63:0] H_write2_c_din;
input   H_write2_c_full_n;
output   H_write2_c_write;
input  [63:0] H_write3;
output  [63:0] H_write3_c_din;
input   H_write3_c_full_n;
output   H_write3_c_write;
input  [63:0] H_write4;
output  [63:0] H_write4_c_din;
input   H_write4_c_full_n;
output   H_write4_c_write;
input  [63:0] H_write5;
output  [63:0] H_write5_c_din;
input   H_write5_c_full_n;
output   H_write5_c_write;
input  [63:0] H_write6;
output  [63:0] H_write6_c_din;
input   H_write6_c_full_n;
output   H_write6_c_write;
input  [63:0] H_write7;
output  [63:0] H_write7_c_din;
input   H_write7_c_full_n;
output   H_write7_c_write;
input  [63:0] H_write8;
output  [63:0] H_write8_c_din;
input   H_write8_c_full_n;
output   H_write8_c_write;
input  [63:0] H_write9;
output  [63:0] H_write9_c_din;
input   H_write9_c_full_n;
output   H_write9_c_write;
input  [63:0] H_write10;
output  [63:0] H_write10_c_din;
input   H_write10_c_full_n;
output   H_write10_c_write;
input  [63:0] H_write11;
output  [63:0] H_write11_c_din;
input   H_write11_c_full_n;
output   H_write11_c_write;
input  [63:0] H_write12;
output  [63:0] H_write12_c_din;
input   H_write12_c_full_n;
output   H_write12_c_write;
input  [63:0] H_write13;
output  [63:0] H_write13_c_din;
input   H_write13_c_full_n;
output   H_write13_c_write;
input  [63:0] H_write14;
output  [63:0] H_write14_c_din;
input   H_write14_c_full_n;
output   H_write14_c_write;
input  [63:0] H_write15;
output  [63:0] H_write15_c_din;
input   H_write15_c_full_n;
output   H_write15_c_write;
input  [31:0] hyperedge_size;
output  [31:0] hyperedge_size_c_din;
input   hyperedge_size_c_full_n;
output   hyperedge_size_c_write;
output  [31:0] hyperedge_size_c71_din;
input   hyperedge_size_c71_full_n;
output   hyperedge_size_c71_write;
output  [31:0] hyperedge_size_c72_din;
input   hyperedge_size_c72_full_n;
output   hyperedge_size_c72_write;
output  [31:0] hyperedge_size_c73_din;
input   hyperedge_size_c73_full_n;
output   hyperedge_size_c73_write;
output  [31:0] hyperedge_size_c74_din;
input   hyperedge_size_c74_full_n;
output   hyperedge_size_c74_write;
output  [31:0] hyperedge_size_c75_din;
input   hyperedge_size_c75_full_n;
output   hyperedge_size_c75_write;
output  [31:0] hyperedge_size_c76_din;
input   hyperedge_size_c76_full_n;
output   hyperedge_size_c76_write;
output  [31:0] hyperedge_size_c77_din;
input   hyperedge_size_c77_full_n;
output   hyperedge_size_c77_write;
output  [31:0] hyperedge_size_c78_din;
input   hyperedge_size_c78_full_n;
output   hyperedge_size_c78_write;
output  [31:0] hyperedge_size_c79_din;
input   hyperedge_size_c79_full_n;
output   hyperedge_size_c79_write;
output  [31:0] hyperedge_size_c80_din;
input   hyperedge_size_c80_full_n;
output   hyperedge_size_c80_write;
output  [31:0] hyperedge_size_c81_din;
input   hyperedge_size_c81_full_n;
output   hyperedge_size_c81_write;
output  [31:0] hyperedge_size_c82_din;
input   hyperedge_size_c82_full_n;
output   hyperedge_size_c82_write;
output  [31:0] hyperedge_size_c83_din;
input   hyperedge_size_c83_full_n;
output   hyperedge_size_c83_write;
output  [31:0] hyperedge_size_c84_din;
input   hyperedge_size_c84_full_n;
output   hyperedge_size_c84_write;
output  [31:0] hyperedge_size_c85_din;
input   hyperedge_size_c85_full_n;
output   hyperedge_size_c85_write;
output   ap_ext_blocking_n;
output   ap_str_blocking_n;
output   ap_int_blocking_n;

reg ap_done;
reg ap_idle;
reg start_write;
reg H_write0_c_write;
reg H_write1_c_write;
reg H_write2_c_write;
reg H_write3_c_write;
reg H_write4_c_write;
reg H_write5_c_write;
reg H_write6_c_write;
reg H_write7_c_write;
reg H_write8_c_write;
reg H_write9_c_write;
reg H_write10_c_write;
reg H_write11_c_write;
reg H_write12_c_write;
reg H_write13_c_write;
reg H_write14_c_write;
reg H_write15_c_write;
reg hyperedge_size_c_write;
reg hyperedge_size_c71_write;
reg hyperedge_size_c72_write;
reg hyperedge_size_c73_write;
reg hyperedge_size_c74_write;
reg hyperedge_size_c75_write;
reg hyperedge_size_c76_write;
reg hyperedge_size_c77_write;
reg hyperedge_size_c78_write;
reg hyperedge_size_c79_write;
reg hyperedge_size_c80_write;
reg hyperedge_size_c81_write;
reg hyperedge_size_c82_write;
reg hyperedge_size_c83_write;
reg hyperedge_size_c84_write;
reg hyperedge_size_c85_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    H_write0_c_blk_n;
reg    H_write1_c_blk_n;
reg    H_write2_c_blk_n;
reg    H_write3_c_blk_n;
reg    H_write4_c_blk_n;
reg    H_write5_c_blk_n;
reg    H_write6_c_blk_n;
reg    H_write7_c_blk_n;
reg    H_write8_c_blk_n;
reg    H_write9_c_blk_n;
reg    H_write10_c_blk_n;
reg    H_write11_c_blk_n;
reg    H_write12_c_blk_n;
reg    H_write13_c_blk_n;
reg    H_write14_c_blk_n;
reg    H_write15_c_blk_n;
reg    hyperedge_size_c_blk_n;
reg    hyperedge_size_c71_blk_n;
reg    hyperedge_size_c72_blk_n;
reg    hyperedge_size_c73_blk_n;
reg    hyperedge_size_c74_blk_n;
reg    hyperedge_size_c75_blk_n;
reg    hyperedge_size_c76_blk_n;
reg    hyperedge_size_c77_blk_n;
reg    hyperedge_size_c78_blk_n;
reg    hyperedge_size_c79_blk_n;
reg    hyperedge_size_c80_blk_n;
reg    hyperedge_size_c81_blk_n;
reg    hyperedge_size_c82_blk_n;
reg    hyperedge_size_c83_blk_n;
reg    hyperedge_size_c84_blk_n;
reg    hyperedge_size_c85_blk_n;
reg    ap_block_state1;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_int_blocking_cur_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((real_start == 1'b0) | (1'b0 == H_write11_c_full_n) | (1'b0 == H_write10_c_full_n) | (1'b0 == H_write9_c_full_n) | (1'b0 == H_write8_c_full_n) | (1'b0 == H_write7_c_full_n) | (1'b0 == H_write6_c_full_n) | (1'b0 == H_write5_c_full_n) | (1'b0 == H_write4_c_full_n) | (1'b0 == H_write3_c_full_n) | (1'b0 == H_write2_c_full_n) | (1'b0 == H_write1_c_full_n) | (1'b0 == H_write0_c_full_n) | (1'b0 == H_write15_c_full_n) | (1'b0 == H_write14_c_full_n) | (1'b0 == H_write13_c_full_n) | (1'b0 == H_write12_c_full_n) | (ap_done_reg == 1'b1) | (hyperedge_size_c85_full_n == 1'b0) | (hyperedge_size_c84_full_n == 1'b0) | (hyperedge_size_c83_full_n == 1'b0) | (hyperedge_size_c82_full_n == 1'b0) | (hyperedge_size_c81_full_n == 1'b0) | (hyperedge_size_c80_full_n == 1'b0) | (hyperedge_size_c79_full_n == 1'b0) | (hyperedge_size_c78_full_n == 1'b0) | (hyperedge_size_c77_full_n == 1'b0) | (hyperedge_size_c76_full_n == 1'b0) | (hyperedge_size_c75_full_n == 1'b0) | (hyperedge_size_c74_full_n == 1'b0) | (hyperedge_size_c73_full_n == 1'b0) | (hyperedge_size_c72_full_n == 1'b0) | (hyperedge_size_c71_full_n == 1'b0) | (hyperedge_size_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        H_write0_c_blk_n = H_write0_c_full_n;
    end else begin
        H_write0_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (1'b0 == H_write11_c_full_n) | (1'b0 == H_write10_c_full_n) | (1'b0 == H_write9_c_full_n) | (1'b0 == H_write8_c_full_n) | (1'b0 == H_write7_c_full_n) | (1'b0 == H_write6_c_full_n) | (1'b0 == H_write5_c_full_n) | (1'b0 == H_write4_c_full_n) | (1'b0 == H_write3_c_full_n) | (1'b0 == H_write2_c_full_n) | (1'b0 == H_write1_c_full_n) | (1'b0 == H_write0_c_full_n) | (1'b0 == H_write15_c_full_n) | (1'b0 == H_write14_c_full_n) | (1'b0 == H_write13_c_full_n) | (1'b0 == H_write12_c_full_n) | (ap_done_reg == 1'b1) | (hyperedge_size_c85_full_n == 1'b0) | (hyperedge_size_c84_full_n == 1'b0) | (hyperedge_size_c83_full_n == 1'b0) | (hyperedge_size_c82_full_n == 1'b0) | (hyperedge_size_c81_full_n == 1'b0) | (hyperedge_size_c80_full_n == 1'b0) | (hyperedge_size_c79_full_n == 1'b0) | (hyperedge_size_c78_full_n == 1'b0) | (hyperedge_size_c77_full_n == 1'b0) | (hyperedge_size_c76_full_n == 1'b0) | (hyperedge_size_c75_full_n == 1'b0) | (hyperedge_size_c74_full_n == 1'b0) | (hyperedge_size_c73_full_n == 1'b0) | (hyperedge_size_c72_full_n == 1'b0) | (hyperedge_size_c71_full_n == 1'b0) | (hyperedge_size_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        H_write0_c_write = 1'b1;
    end else begin
        H_write0_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        H_write10_c_blk_n = H_write10_c_full_n;
    end else begin
        H_write10_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (1'b0 == H_write11_c_full_n) | (1'b0 == H_write10_c_full_n) | (1'b0 == H_write9_c_full_n) | (1'b0 == H_write8_c_full_n) | (1'b0 == H_write7_c_full_n) | (1'b0 == H_write6_c_full_n) | (1'b0 == H_write5_c_full_n) | (1'b0 == H_write4_c_full_n) | (1'b0 == H_write3_c_full_n) | (1'b0 == H_write2_c_full_n) | (1'b0 == H_write1_c_full_n) | (1'b0 == H_write0_c_full_n) | (1'b0 == H_write15_c_full_n) | (1'b0 == H_write14_c_full_n) | (1'b0 == H_write13_c_full_n) | (1'b0 == H_write12_c_full_n) | (ap_done_reg == 1'b1) | (hyperedge_size_c85_full_n == 1'b0) | (hyperedge_size_c84_full_n == 1'b0) | (hyperedge_size_c83_full_n == 1'b0) | (hyperedge_size_c82_full_n == 1'b0) | (hyperedge_size_c81_full_n == 1'b0) | (hyperedge_size_c80_full_n == 1'b0) | (hyperedge_size_c79_full_n == 1'b0) | (hyperedge_size_c78_full_n == 1'b0) | (hyperedge_size_c77_full_n == 1'b0) | (hyperedge_size_c76_full_n == 1'b0) | (hyperedge_size_c75_full_n == 1'b0) | (hyperedge_size_c74_full_n == 1'b0) | (hyperedge_size_c73_full_n == 1'b0) | (hyperedge_size_c72_full_n == 1'b0) | (hyperedge_size_c71_full_n == 1'b0) | (hyperedge_size_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        H_write10_c_write = 1'b1;
    end else begin
        H_write10_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        H_write11_c_blk_n = H_write11_c_full_n;
    end else begin
        H_write11_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (1'b0 == H_write11_c_full_n) | (1'b0 == H_write10_c_full_n) | (1'b0 == H_write9_c_full_n) | (1'b0 == H_write8_c_full_n) | (1'b0 == H_write7_c_full_n) | (1'b0 == H_write6_c_full_n) | (1'b0 == H_write5_c_full_n) | (1'b0 == H_write4_c_full_n) | (1'b0 == H_write3_c_full_n) | (1'b0 == H_write2_c_full_n) | (1'b0 == H_write1_c_full_n) | (1'b0 == H_write0_c_full_n) | (1'b0 == H_write15_c_full_n) | (1'b0 == H_write14_c_full_n) | (1'b0 == H_write13_c_full_n) | (1'b0 == H_write12_c_full_n) | (ap_done_reg == 1'b1) | (hyperedge_size_c85_full_n == 1'b0) | (hyperedge_size_c84_full_n == 1'b0) | (hyperedge_size_c83_full_n == 1'b0) | (hyperedge_size_c82_full_n == 1'b0) | (hyperedge_size_c81_full_n == 1'b0) | (hyperedge_size_c80_full_n == 1'b0) | (hyperedge_size_c79_full_n == 1'b0) | (hyperedge_size_c78_full_n == 1'b0) | (hyperedge_size_c77_full_n == 1'b0) | (hyperedge_size_c76_full_n == 1'b0) | (hyperedge_size_c75_full_n == 1'b0) | (hyperedge_size_c74_full_n == 1'b0) | (hyperedge_size_c73_full_n == 1'b0) | (hyperedge_size_c72_full_n == 1'b0) | (hyperedge_size_c71_full_n == 1'b0) | (hyperedge_size_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        H_write11_c_write = 1'b1;
    end else begin
        H_write11_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        H_write12_c_blk_n = H_write12_c_full_n;
    end else begin
        H_write12_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (1'b0 == H_write11_c_full_n) | (1'b0 == H_write10_c_full_n) | (1'b0 == H_write9_c_full_n) | (1'b0 == H_write8_c_full_n) | (1'b0 == H_write7_c_full_n) | (1'b0 == H_write6_c_full_n) | (1'b0 == H_write5_c_full_n) | (1'b0 == H_write4_c_full_n) | (1'b0 == H_write3_c_full_n) | (1'b0 == H_write2_c_full_n) | (1'b0 == H_write1_c_full_n) | (1'b0 == H_write0_c_full_n) | (1'b0 == H_write15_c_full_n) | (1'b0 == H_write14_c_full_n) | (1'b0 == H_write13_c_full_n) | (1'b0 == H_write12_c_full_n) | (ap_done_reg == 1'b1) | (hyperedge_size_c85_full_n == 1'b0) | (hyperedge_size_c84_full_n == 1'b0) | (hyperedge_size_c83_full_n == 1'b0) | (hyperedge_size_c82_full_n == 1'b0) | (hyperedge_size_c81_full_n == 1'b0) | (hyperedge_size_c80_full_n == 1'b0) | (hyperedge_size_c79_full_n == 1'b0) | (hyperedge_size_c78_full_n == 1'b0) | (hyperedge_size_c77_full_n == 1'b0) | (hyperedge_size_c76_full_n == 1'b0) | (hyperedge_size_c75_full_n == 1'b0) | (hyperedge_size_c74_full_n == 1'b0) | (hyperedge_size_c73_full_n == 1'b0) | (hyperedge_size_c72_full_n == 1'b0) | (hyperedge_size_c71_full_n == 1'b0) | (hyperedge_size_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        H_write12_c_write = 1'b1;
    end else begin
        H_write12_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        H_write13_c_blk_n = H_write13_c_full_n;
    end else begin
        H_write13_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (1'b0 == H_write11_c_full_n) | (1'b0 == H_write10_c_full_n) | (1'b0 == H_write9_c_full_n) | (1'b0 == H_write8_c_full_n) | (1'b0 == H_write7_c_full_n) | (1'b0 == H_write6_c_full_n) | (1'b0 == H_write5_c_full_n) | (1'b0 == H_write4_c_full_n) | (1'b0 == H_write3_c_full_n) | (1'b0 == H_write2_c_full_n) | (1'b0 == H_write1_c_full_n) | (1'b0 == H_write0_c_full_n) | (1'b0 == H_write15_c_full_n) | (1'b0 == H_write14_c_full_n) | (1'b0 == H_write13_c_full_n) | (1'b0 == H_write12_c_full_n) | (ap_done_reg == 1'b1) | (hyperedge_size_c85_full_n == 1'b0) | (hyperedge_size_c84_full_n == 1'b0) | (hyperedge_size_c83_full_n == 1'b0) | (hyperedge_size_c82_full_n == 1'b0) | (hyperedge_size_c81_full_n == 1'b0) | (hyperedge_size_c80_full_n == 1'b0) | (hyperedge_size_c79_full_n == 1'b0) | (hyperedge_size_c78_full_n == 1'b0) | (hyperedge_size_c77_full_n == 1'b0) | (hyperedge_size_c76_full_n == 1'b0) | (hyperedge_size_c75_full_n == 1'b0) | (hyperedge_size_c74_full_n == 1'b0) | (hyperedge_size_c73_full_n == 1'b0) | (hyperedge_size_c72_full_n == 1'b0) | (hyperedge_size_c71_full_n == 1'b0) | (hyperedge_size_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        H_write13_c_write = 1'b1;
    end else begin
        H_write13_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        H_write14_c_blk_n = H_write14_c_full_n;
    end else begin
        H_write14_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (1'b0 == H_write11_c_full_n) | (1'b0 == H_write10_c_full_n) | (1'b0 == H_write9_c_full_n) | (1'b0 == H_write8_c_full_n) | (1'b0 == H_write7_c_full_n) | (1'b0 == H_write6_c_full_n) | (1'b0 == H_write5_c_full_n) | (1'b0 == H_write4_c_full_n) | (1'b0 == H_write3_c_full_n) | (1'b0 == H_write2_c_full_n) | (1'b0 == H_write1_c_full_n) | (1'b0 == H_write0_c_full_n) | (1'b0 == H_write15_c_full_n) | (1'b0 == H_write14_c_full_n) | (1'b0 == H_write13_c_full_n) | (1'b0 == H_write12_c_full_n) | (ap_done_reg == 1'b1) | (hyperedge_size_c85_full_n == 1'b0) | (hyperedge_size_c84_full_n == 1'b0) | (hyperedge_size_c83_full_n == 1'b0) | (hyperedge_size_c82_full_n == 1'b0) | (hyperedge_size_c81_full_n == 1'b0) | (hyperedge_size_c80_full_n == 1'b0) | (hyperedge_size_c79_full_n == 1'b0) | (hyperedge_size_c78_full_n == 1'b0) | (hyperedge_size_c77_full_n == 1'b0) | (hyperedge_size_c76_full_n == 1'b0) | (hyperedge_size_c75_full_n == 1'b0) | (hyperedge_size_c74_full_n == 1'b0) | (hyperedge_size_c73_full_n == 1'b0) | (hyperedge_size_c72_full_n == 1'b0) | (hyperedge_size_c71_full_n == 1'b0) | (hyperedge_size_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        H_write14_c_write = 1'b1;
    end else begin
        H_write14_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        H_write15_c_blk_n = H_write15_c_full_n;
    end else begin
        H_write15_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (1'b0 == H_write11_c_full_n) | (1'b0 == H_write10_c_full_n) | (1'b0 == H_write9_c_full_n) | (1'b0 == H_write8_c_full_n) | (1'b0 == H_write7_c_full_n) | (1'b0 == H_write6_c_full_n) | (1'b0 == H_write5_c_full_n) | (1'b0 == H_write4_c_full_n) | (1'b0 == H_write3_c_full_n) | (1'b0 == H_write2_c_full_n) | (1'b0 == H_write1_c_full_n) | (1'b0 == H_write0_c_full_n) | (1'b0 == H_write15_c_full_n) | (1'b0 == H_write14_c_full_n) | (1'b0 == H_write13_c_full_n) | (1'b0 == H_write12_c_full_n) | (ap_done_reg == 1'b1) | (hyperedge_size_c85_full_n == 1'b0) | (hyperedge_size_c84_full_n == 1'b0) | (hyperedge_size_c83_full_n == 1'b0) | (hyperedge_size_c82_full_n == 1'b0) | (hyperedge_size_c81_full_n == 1'b0) | (hyperedge_size_c80_full_n == 1'b0) | (hyperedge_size_c79_full_n == 1'b0) | (hyperedge_size_c78_full_n == 1'b0) | (hyperedge_size_c77_full_n == 1'b0) | (hyperedge_size_c76_full_n == 1'b0) | (hyperedge_size_c75_full_n == 1'b0) | (hyperedge_size_c74_full_n == 1'b0) | (hyperedge_size_c73_full_n == 1'b0) | (hyperedge_size_c72_full_n == 1'b0) | (hyperedge_size_c71_full_n == 1'b0) | (hyperedge_size_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        H_write15_c_write = 1'b1;
    end else begin
        H_write15_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        H_write1_c_blk_n = H_write1_c_full_n;
    end else begin
        H_write1_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (1'b0 == H_write11_c_full_n) | (1'b0 == H_write10_c_full_n) | (1'b0 == H_write9_c_full_n) | (1'b0 == H_write8_c_full_n) | (1'b0 == H_write7_c_full_n) | (1'b0 == H_write6_c_full_n) | (1'b0 == H_write5_c_full_n) | (1'b0 == H_write4_c_full_n) | (1'b0 == H_write3_c_full_n) | (1'b0 == H_write2_c_full_n) | (1'b0 == H_write1_c_full_n) | (1'b0 == H_write0_c_full_n) | (1'b0 == H_write15_c_full_n) | (1'b0 == H_write14_c_full_n) | (1'b0 == H_write13_c_full_n) | (1'b0 == H_write12_c_full_n) | (ap_done_reg == 1'b1) | (hyperedge_size_c85_full_n == 1'b0) | (hyperedge_size_c84_full_n == 1'b0) | (hyperedge_size_c83_full_n == 1'b0) | (hyperedge_size_c82_full_n == 1'b0) | (hyperedge_size_c81_full_n == 1'b0) | (hyperedge_size_c80_full_n == 1'b0) | (hyperedge_size_c79_full_n == 1'b0) | (hyperedge_size_c78_full_n == 1'b0) | (hyperedge_size_c77_full_n == 1'b0) | (hyperedge_size_c76_full_n == 1'b0) | (hyperedge_size_c75_full_n == 1'b0) | (hyperedge_size_c74_full_n == 1'b0) | (hyperedge_size_c73_full_n == 1'b0) | (hyperedge_size_c72_full_n == 1'b0) | (hyperedge_size_c71_full_n == 1'b0) | (hyperedge_size_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        H_write1_c_write = 1'b1;
    end else begin
        H_write1_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        H_write2_c_blk_n = H_write2_c_full_n;
    end else begin
        H_write2_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (1'b0 == H_write11_c_full_n) | (1'b0 == H_write10_c_full_n) | (1'b0 == H_write9_c_full_n) | (1'b0 == H_write8_c_full_n) | (1'b0 == H_write7_c_full_n) | (1'b0 == H_write6_c_full_n) | (1'b0 == H_write5_c_full_n) | (1'b0 == H_write4_c_full_n) | (1'b0 == H_write3_c_full_n) | (1'b0 == H_write2_c_full_n) | (1'b0 == H_write1_c_full_n) | (1'b0 == H_write0_c_full_n) | (1'b0 == H_write15_c_full_n) | (1'b0 == H_write14_c_full_n) | (1'b0 == H_write13_c_full_n) | (1'b0 == H_write12_c_full_n) | (ap_done_reg == 1'b1) | (hyperedge_size_c85_full_n == 1'b0) | (hyperedge_size_c84_full_n == 1'b0) | (hyperedge_size_c83_full_n == 1'b0) | (hyperedge_size_c82_full_n == 1'b0) | (hyperedge_size_c81_full_n == 1'b0) | (hyperedge_size_c80_full_n == 1'b0) | (hyperedge_size_c79_full_n == 1'b0) | (hyperedge_size_c78_full_n == 1'b0) | (hyperedge_size_c77_full_n == 1'b0) | (hyperedge_size_c76_full_n == 1'b0) | (hyperedge_size_c75_full_n == 1'b0) | (hyperedge_size_c74_full_n == 1'b0) | (hyperedge_size_c73_full_n == 1'b0) | (hyperedge_size_c72_full_n == 1'b0) | (hyperedge_size_c71_full_n == 1'b0) | (hyperedge_size_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        H_write2_c_write = 1'b1;
    end else begin
        H_write2_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        H_write3_c_blk_n = H_write3_c_full_n;
    end else begin
        H_write3_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (1'b0 == H_write11_c_full_n) | (1'b0 == H_write10_c_full_n) | (1'b0 == H_write9_c_full_n) | (1'b0 == H_write8_c_full_n) | (1'b0 == H_write7_c_full_n) | (1'b0 == H_write6_c_full_n) | (1'b0 == H_write5_c_full_n) | (1'b0 == H_write4_c_full_n) | (1'b0 == H_write3_c_full_n) | (1'b0 == H_write2_c_full_n) | (1'b0 == H_write1_c_full_n) | (1'b0 == H_write0_c_full_n) | (1'b0 == H_write15_c_full_n) | (1'b0 == H_write14_c_full_n) | (1'b0 == H_write13_c_full_n) | (1'b0 == H_write12_c_full_n) | (ap_done_reg == 1'b1) | (hyperedge_size_c85_full_n == 1'b0) | (hyperedge_size_c84_full_n == 1'b0) | (hyperedge_size_c83_full_n == 1'b0) | (hyperedge_size_c82_full_n == 1'b0) | (hyperedge_size_c81_full_n == 1'b0) | (hyperedge_size_c80_full_n == 1'b0) | (hyperedge_size_c79_full_n == 1'b0) | (hyperedge_size_c78_full_n == 1'b0) | (hyperedge_size_c77_full_n == 1'b0) | (hyperedge_size_c76_full_n == 1'b0) | (hyperedge_size_c75_full_n == 1'b0) | (hyperedge_size_c74_full_n == 1'b0) | (hyperedge_size_c73_full_n == 1'b0) | (hyperedge_size_c72_full_n == 1'b0) | (hyperedge_size_c71_full_n == 1'b0) | (hyperedge_size_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        H_write3_c_write = 1'b1;
    end else begin
        H_write3_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        H_write4_c_blk_n = H_write4_c_full_n;
    end else begin
        H_write4_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (1'b0 == H_write11_c_full_n) | (1'b0 == H_write10_c_full_n) | (1'b0 == H_write9_c_full_n) | (1'b0 == H_write8_c_full_n) | (1'b0 == H_write7_c_full_n) | (1'b0 == H_write6_c_full_n) | (1'b0 == H_write5_c_full_n) | (1'b0 == H_write4_c_full_n) | (1'b0 == H_write3_c_full_n) | (1'b0 == H_write2_c_full_n) | (1'b0 == H_write1_c_full_n) | (1'b0 == H_write0_c_full_n) | (1'b0 == H_write15_c_full_n) | (1'b0 == H_write14_c_full_n) | (1'b0 == H_write13_c_full_n) | (1'b0 == H_write12_c_full_n) | (ap_done_reg == 1'b1) | (hyperedge_size_c85_full_n == 1'b0) | (hyperedge_size_c84_full_n == 1'b0) | (hyperedge_size_c83_full_n == 1'b0) | (hyperedge_size_c82_full_n == 1'b0) | (hyperedge_size_c81_full_n == 1'b0) | (hyperedge_size_c80_full_n == 1'b0) | (hyperedge_size_c79_full_n == 1'b0) | (hyperedge_size_c78_full_n == 1'b0) | (hyperedge_size_c77_full_n == 1'b0) | (hyperedge_size_c76_full_n == 1'b0) | (hyperedge_size_c75_full_n == 1'b0) | (hyperedge_size_c74_full_n == 1'b0) | (hyperedge_size_c73_full_n == 1'b0) | (hyperedge_size_c72_full_n == 1'b0) | (hyperedge_size_c71_full_n == 1'b0) | (hyperedge_size_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        H_write4_c_write = 1'b1;
    end else begin
        H_write4_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        H_write5_c_blk_n = H_write5_c_full_n;
    end else begin
        H_write5_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (1'b0 == H_write11_c_full_n) | (1'b0 == H_write10_c_full_n) | (1'b0 == H_write9_c_full_n) | (1'b0 == H_write8_c_full_n) | (1'b0 == H_write7_c_full_n) | (1'b0 == H_write6_c_full_n) | (1'b0 == H_write5_c_full_n) | (1'b0 == H_write4_c_full_n) | (1'b0 == H_write3_c_full_n) | (1'b0 == H_write2_c_full_n) | (1'b0 == H_write1_c_full_n) | (1'b0 == H_write0_c_full_n) | (1'b0 == H_write15_c_full_n) | (1'b0 == H_write14_c_full_n) | (1'b0 == H_write13_c_full_n) | (1'b0 == H_write12_c_full_n) | (ap_done_reg == 1'b1) | (hyperedge_size_c85_full_n == 1'b0) | (hyperedge_size_c84_full_n == 1'b0) | (hyperedge_size_c83_full_n == 1'b0) | (hyperedge_size_c82_full_n == 1'b0) | (hyperedge_size_c81_full_n == 1'b0) | (hyperedge_size_c80_full_n == 1'b0) | (hyperedge_size_c79_full_n == 1'b0) | (hyperedge_size_c78_full_n == 1'b0) | (hyperedge_size_c77_full_n == 1'b0) | (hyperedge_size_c76_full_n == 1'b0) | (hyperedge_size_c75_full_n == 1'b0) | (hyperedge_size_c74_full_n == 1'b0) | (hyperedge_size_c73_full_n == 1'b0) | (hyperedge_size_c72_full_n == 1'b0) | (hyperedge_size_c71_full_n == 1'b0) | (hyperedge_size_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        H_write5_c_write = 1'b1;
    end else begin
        H_write5_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        H_write6_c_blk_n = H_write6_c_full_n;
    end else begin
        H_write6_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (1'b0 == H_write11_c_full_n) | (1'b0 == H_write10_c_full_n) | (1'b0 == H_write9_c_full_n) | (1'b0 == H_write8_c_full_n) | (1'b0 == H_write7_c_full_n) | (1'b0 == H_write6_c_full_n) | (1'b0 == H_write5_c_full_n) | (1'b0 == H_write4_c_full_n) | (1'b0 == H_write3_c_full_n) | (1'b0 == H_write2_c_full_n) | (1'b0 == H_write1_c_full_n) | (1'b0 == H_write0_c_full_n) | (1'b0 == H_write15_c_full_n) | (1'b0 == H_write14_c_full_n) | (1'b0 == H_write13_c_full_n) | (1'b0 == H_write12_c_full_n) | (ap_done_reg == 1'b1) | (hyperedge_size_c85_full_n == 1'b0) | (hyperedge_size_c84_full_n == 1'b0) | (hyperedge_size_c83_full_n == 1'b0) | (hyperedge_size_c82_full_n == 1'b0) | (hyperedge_size_c81_full_n == 1'b0) | (hyperedge_size_c80_full_n == 1'b0) | (hyperedge_size_c79_full_n == 1'b0) | (hyperedge_size_c78_full_n == 1'b0) | (hyperedge_size_c77_full_n == 1'b0) | (hyperedge_size_c76_full_n == 1'b0) | (hyperedge_size_c75_full_n == 1'b0) | (hyperedge_size_c74_full_n == 1'b0) | (hyperedge_size_c73_full_n == 1'b0) | (hyperedge_size_c72_full_n == 1'b0) | (hyperedge_size_c71_full_n == 1'b0) | (hyperedge_size_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        H_write6_c_write = 1'b1;
    end else begin
        H_write6_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        H_write7_c_blk_n = H_write7_c_full_n;
    end else begin
        H_write7_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (1'b0 == H_write11_c_full_n) | (1'b0 == H_write10_c_full_n) | (1'b0 == H_write9_c_full_n) | (1'b0 == H_write8_c_full_n) | (1'b0 == H_write7_c_full_n) | (1'b0 == H_write6_c_full_n) | (1'b0 == H_write5_c_full_n) | (1'b0 == H_write4_c_full_n) | (1'b0 == H_write3_c_full_n) | (1'b0 == H_write2_c_full_n) | (1'b0 == H_write1_c_full_n) | (1'b0 == H_write0_c_full_n) | (1'b0 == H_write15_c_full_n) | (1'b0 == H_write14_c_full_n) | (1'b0 == H_write13_c_full_n) | (1'b0 == H_write12_c_full_n) | (ap_done_reg == 1'b1) | (hyperedge_size_c85_full_n == 1'b0) | (hyperedge_size_c84_full_n == 1'b0) | (hyperedge_size_c83_full_n == 1'b0) | (hyperedge_size_c82_full_n == 1'b0) | (hyperedge_size_c81_full_n == 1'b0) | (hyperedge_size_c80_full_n == 1'b0) | (hyperedge_size_c79_full_n == 1'b0) | (hyperedge_size_c78_full_n == 1'b0) | (hyperedge_size_c77_full_n == 1'b0) | (hyperedge_size_c76_full_n == 1'b0) | (hyperedge_size_c75_full_n == 1'b0) | (hyperedge_size_c74_full_n == 1'b0) | (hyperedge_size_c73_full_n == 1'b0) | (hyperedge_size_c72_full_n == 1'b0) | (hyperedge_size_c71_full_n == 1'b0) | (hyperedge_size_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        H_write7_c_write = 1'b1;
    end else begin
        H_write7_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        H_write8_c_blk_n = H_write8_c_full_n;
    end else begin
        H_write8_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (1'b0 == H_write11_c_full_n) | (1'b0 == H_write10_c_full_n) | (1'b0 == H_write9_c_full_n) | (1'b0 == H_write8_c_full_n) | (1'b0 == H_write7_c_full_n) | (1'b0 == H_write6_c_full_n) | (1'b0 == H_write5_c_full_n) | (1'b0 == H_write4_c_full_n) | (1'b0 == H_write3_c_full_n) | (1'b0 == H_write2_c_full_n) | (1'b0 == H_write1_c_full_n) | (1'b0 == H_write0_c_full_n) | (1'b0 == H_write15_c_full_n) | (1'b0 == H_write14_c_full_n) | (1'b0 == H_write13_c_full_n) | (1'b0 == H_write12_c_full_n) | (ap_done_reg == 1'b1) | (hyperedge_size_c85_full_n == 1'b0) | (hyperedge_size_c84_full_n == 1'b0) | (hyperedge_size_c83_full_n == 1'b0) | (hyperedge_size_c82_full_n == 1'b0) | (hyperedge_size_c81_full_n == 1'b0) | (hyperedge_size_c80_full_n == 1'b0) | (hyperedge_size_c79_full_n == 1'b0) | (hyperedge_size_c78_full_n == 1'b0) | (hyperedge_size_c77_full_n == 1'b0) | (hyperedge_size_c76_full_n == 1'b0) | (hyperedge_size_c75_full_n == 1'b0) | (hyperedge_size_c74_full_n == 1'b0) | (hyperedge_size_c73_full_n == 1'b0) | (hyperedge_size_c72_full_n == 1'b0) | (hyperedge_size_c71_full_n == 1'b0) | (hyperedge_size_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        H_write8_c_write = 1'b1;
    end else begin
        H_write8_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        H_write9_c_blk_n = H_write9_c_full_n;
    end else begin
        H_write9_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (1'b0 == H_write11_c_full_n) | (1'b0 == H_write10_c_full_n) | (1'b0 == H_write9_c_full_n) | (1'b0 == H_write8_c_full_n) | (1'b0 == H_write7_c_full_n) | (1'b0 == H_write6_c_full_n) | (1'b0 == H_write5_c_full_n) | (1'b0 == H_write4_c_full_n) | (1'b0 == H_write3_c_full_n) | (1'b0 == H_write2_c_full_n) | (1'b0 == H_write1_c_full_n) | (1'b0 == H_write0_c_full_n) | (1'b0 == H_write15_c_full_n) | (1'b0 == H_write14_c_full_n) | (1'b0 == H_write13_c_full_n) | (1'b0 == H_write12_c_full_n) | (ap_done_reg == 1'b1) | (hyperedge_size_c85_full_n == 1'b0) | (hyperedge_size_c84_full_n == 1'b0) | (hyperedge_size_c83_full_n == 1'b0) | (hyperedge_size_c82_full_n == 1'b0) | (hyperedge_size_c81_full_n == 1'b0) | (hyperedge_size_c80_full_n == 1'b0) | (hyperedge_size_c79_full_n == 1'b0) | (hyperedge_size_c78_full_n == 1'b0) | (hyperedge_size_c77_full_n == 1'b0) | (hyperedge_size_c76_full_n == 1'b0) | (hyperedge_size_c75_full_n == 1'b0) | (hyperedge_size_c74_full_n == 1'b0) | (hyperedge_size_c73_full_n == 1'b0) | (hyperedge_size_c72_full_n == 1'b0) | (hyperedge_size_c71_full_n == 1'b0) | (hyperedge_size_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        H_write9_c_write = 1'b1;
    end else begin
        H_write9_c_write = 1'b0;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) | (1'b0 == H_write11_c_full_n) | (1'b0 == H_write10_c_full_n) | (1'b0 == H_write9_c_full_n) | (1'b0 == H_write8_c_full_n) | (1'b0 == H_write7_c_full_n) | (1'b0 == H_write6_c_full_n) | (1'b0 == H_write5_c_full_n) | (1'b0 == H_write4_c_full_n) | (1'b0 == H_write3_c_full_n) | (1'b0 == H_write2_c_full_n) | (1'b0 == H_write1_c_full_n) | (1'b0 == H_write0_c_full_n) | (1'b0 == H_write15_c_full_n) | (1'b0 == H_write14_c_full_n) | (1'b0 == H_write13_c_full_n) | (1'b0 == H_write12_c_full_n) | (ap_done_reg == 1'b1) | (hyperedge_size_c85_full_n == 1'b0) | (hyperedge_size_c84_full_n == 1'b0) | (hyperedge_size_c83_full_n == 1'b0) | (hyperedge_size_c82_full_n == 1'b0) | (hyperedge_size_c81_full_n == 1'b0) | (hyperedge_size_c80_full_n == 1'b0) | (hyperedge_size_c79_full_n == 1'b0) | (hyperedge_size_c78_full_n == 1'b0) | (hyperedge_size_c77_full_n == 1'b0) | (hyperedge_size_c76_full_n == 1'b0) | (hyperedge_size_c75_full_n == 1'b0) | (hyperedge_size_c74_full_n == 1'b0) | (hyperedge_size_c73_full_n == 1'b0) | (hyperedge_size_c72_full_n == 1'b0) | (hyperedge_size_c71_full_n == 1'b0) | (hyperedge_size_c_full_n == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (1'b0 == H_write11_c_full_n) | (1'b0 == H_write10_c_full_n) | (1'b0 == H_write9_c_full_n) | (1'b0 == H_write8_c_full_n) | (1'b0 == H_write7_c_full_n) | (1'b0 == H_write6_c_full_n) | (1'b0 == H_write5_c_full_n) | (1'b0 == H_write4_c_full_n) | (1'b0 == H_write3_c_full_n) | (1'b0 == H_write2_c_full_n) | (1'b0 == H_write1_c_full_n) | (1'b0 == H_write0_c_full_n) | (1'b0 == H_write15_c_full_n) | (1'b0 == H_write14_c_full_n) | (1'b0 == H_write13_c_full_n) | (1'b0 == H_write12_c_full_n) | (ap_done_reg == 1'b1) | (hyperedge_size_c85_full_n == 1'b0) | (hyperedge_size_c84_full_n == 1'b0) | (hyperedge_size_c83_full_n == 1'b0) | (hyperedge_size_c82_full_n == 1'b0) | (hyperedge_size_c81_full_n == 1'b0) | (hyperedge_size_c80_full_n == 1'b0) | (hyperedge_size_c79_full_n == 1'b0) | (hyperedge_size_c78_full_n == 1'b0) | (hyperedge_size_c77_full_n == 1'b0) | (hyperedge_size_c76_full_n == 1'b0) | (hyperedge_size_c75_full_n == 1'b0) | (hyperedge_size_c74_full_n == 1'b0) | (hyperedge_size_c73_full_n == 1'b0) | (hyperedge_size_c72_full_n == 1'b0) | (hyperedge_size_c71_full_n == 1'b0) | (hyperedge_size_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        hyperedge_size_c71_blk_n = hyperedge_size_c71_full_n;
    end else begin
        hyperedge_size_c71_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (1'b0 == H_write11_c_full_n) | (1'b0 == H_write10_c_full_n) | (1'b0 == H_write9_c_full_n) | (1'b0 == H_write8_c_full_n) | (1'b0 == H_write7_c_full_n) | (1'b0 == H_write6_c_full_n) | (1'b0 == H_write5_c_full_n) | (1'b0 == H_write4_c_full_n) | (1'b0 == H_write3_c_full_n) | (1'b0 == H_write2_c_full_n) | (1'b0 == H_write1_c_full_n) | (1'b0 == H_write0_c_full_n) | (1'b0 == H_write15_c_full_n) | (1'b0 == H_write14_c_full_n) | (1'b0 == H_write13_c_full_n) | (1'b0 == H_write12_c_full_n) | (ap_done_reg == 1'b1) | (hyperedge_size_c85_full_n == 1'b0) | (hyperedge_size_c84_full_n == 1'b0) | (hyperedge_size_c83_full_n == 1'b0) | (hyperedge_size_c82_full_n == 1'b0) | (hyperedge_size_c81_full_n == 1'b0) | (hyperedge_size_c80_full_n == 1'b0) | (hyperedge_size_c79_full_n == 1'b0) | (hyperedge_size_c78_full_n == 1'b0) | (hyperedge_size_c77_full_n == 1'b0) | (hyperedge_size_c76_full_n == 1'b0) | (hyperedge_size_c75_full_n == 1'b0) | (hyperedge_size_c74_full_n == 1'b0) | (hyperedge_size_c73_full_n == 1'b0) | (hyperedge_size_c72_full_n == 1'b0) | (hyperedge_size_c71_full_n == 1'b0) | (hyperedge_size_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hyperedge_size_c71_write = 1'b1;
    end else begin
        hyperedge_size_c71_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        hyperedge_size_c72_blk_n = hyperedge_size_c72_full_n;
    end else begin
        hyperedge_size_c72_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (1'b0 == H_write11_c_full_n) | (1'b0 == H_write10_c_full_n) | (1'b0 == H_write9_c_full_n) | (1'b0 == H_write8_c_full_n) | (1'b0 == H_write7_c_full_n) | (1'b0 == H_write6_c_full_n) | (1'b0 == H_write5_c_full_n) | (1'b0 == H_write4_c_full_n) | (1'b0 == H_write3_c_full_n) | (1'b0 == H_write2_c_full_n) | (1'b0 == H_write1_c_full_n) | (1'b0 == H_write0_c_full_n) | (1'b0 == H_write15_c_full_n) | (1'b0 == H_write14_c_full_n) | (1'b0 == H_write13_c_full_n) | (1'b0 == H_write12_c_full_n) | (ap_done_reg == 1'b1) | (hyperedge_size_c85_full_n == 1'b0) | (hyperedge_size_c84_full_n == 1'b0) | (hyperedge_size_c83_full_n == 1'b0) | (hyperedge_size_c82_full_n == 1'b0) | (hyperedge_size_c81_full_n == 1'b0) | (hyperedge_size_c80_full_n == 1'b0) | (hyperedge_size_c79_full_n == 1'b0) | (hyperedge_size_c78_full_n == 1'b0) | (hyperedge_size_c77_full_n == 1'b0) | (hyperedge_size_c76_full_n == 1'b0) | (hyperedge_size_c75_full_n == 1'b0) | (hyperedge_size_c74_full_n == 1'b0) | (hyperedge_size_c73_full_n == 1'b0) | (hyperedge_size_c72_full_n == 1'b0) | (hyperedge_size_c71_full_n == 1'b0) | (hyperedge_size_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hyperedge_size_c72_write = 1'b1;
    end else begin
        hyperedge_size_c72_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        hyperedge_size_c73_blk_n = hyperedge_size_c73_full_n;
    end else begin
        hyperedge_size_c73_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (1'b0 == H_write11_c_full_n) | (1'b0 == H_write10_c_full_n) | (1'b0 == H_write9_c_full_n) | (1'b0 == H_write8_c_full_n) | (1'b0 == H_write7_c_full_n) | (1'b0 == H_write6_c_full_n) | (1'b0 == H_write5_c_full_n) | (1'b0 == H_write4_c_full_n) | (1'b0 == H_write3_c_full_n) | (1'b0 == H_write2_c_full_n) | (1'b0 == H_write1_c_full_n) | (1'b0 == H_write0_c_full_n) | (1'b0 == H_write15_c_full_n) | (1'b0 == H_write14_c_full_n) | (1'b0 == H_write13_c_full_n) | (1'b0 == H_write12_c_full_n) | (ap_done_reg == 1'b1) | (hyperedge_size_c85_full_n == 1'b0) | (hyperedge_size_c84_full_n == 1'b0) | (hyperedge_size_c83_full_n == 1'b0) | (hyperedge_size_c82_full_n == 1'b0) | (hyperedge_size_c81_full_n == 1'b0) | (hyperedge_size_c80_full_n == 1'b0) | (hyperedge_size_c79_full_n == 1'b0) | (hyperedge_size_c78_full_n == 1'b0) | (hyperedge_size_c77_full_n == 1'b0) | (hyperedge_size_c76_full_n == 1'b0) | (hyperedge_size_c75_full_n == 1'b0) | (hyperedge_size_c74_full_n == 1'b0) | (hyperedge_size_c73_full_n == 1'b0) | (hyperedge_size_c72_full_n == 1'b0) | (hyperedge_size_c71_full_n == 1'b0) | (hyperedge_size_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hyperedge_size_c73_write = 1'b1;
    end else begin
        hyperedge_size_c73_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        hyperedge_size_c74_blk_n = hyperedge_size_c74_full_n;
    end else begin
        hyperedge_size_c74_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (1'b0 == H_write11_c_full_n) | (1'b0 == H_write10_c_full_n) | (1'b0 == H_write9_c_full_n) | (1'b0 == H_write8_c_full_n) | (1'b0 == H_write7_c_full_n) | (1'b0 == H_write6_c_full_n) | (1'b0 == H_write5_c_full_n) | (1'b0 == H_write4_c_full_n) | (1'b0 == H_write3_c_full_n) | (1'b0 == H_write2_c_full_n) | (1'b0 == H_write1_c_full_n) | (1'b0 == H_write0_c_full_n) | (1'b0 == H_write15_c_full_n) | (1'b0 == H_write14_c_full_n) | (1'b0 == H_write13_c_full_n) | (1'b0 == H_write12_c_full_n) | (ap_done_reg == 1'b1) | (hyperedge_size_c85_full_n == 1'b0) | (hyperedge_size_c84_full_n == 1'b0) | (hyperedge_size_c83_full_n == 1'b0) | (hyperedge_size_c82_full_n == 1'b0) | (hyperedge_size_c81_full_n == 1'b0) | (hyperedge_size_c80_full_n == 1'b0) | (hyperedge_size_c79_full_n == 1'b0) | (hyperedge_size_c78_full_n == 1'b0) | (hyperedge_size_c77_full_n == 1'b0) | (hyperedge_size_c76_full_n == 1'b0) | (hyperedge_size_c75_full_n == 1'b0) | (hyperedge_size_c74_full_n == 1'b0) | (hyperedge_size_c73_full_n == 1'b0) | (hyperedge_size_c72_full_n == 1'b0) | (hyperedge_size_c71_full_n == 1'b0) | (hyperedge_size_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hyperedge_size_c74_write = 1'b1;
    end else begin
        hyperedge_size_c74_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        hyperedge_size_c75_blk_n = hyperedge_size_c75_full_n;
    end else begin
        hyperedge_size_c75_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (1'b0 == H_write11_c_full_n) | (1'b0 == H_write10_c_full_n) | (1'b0 == H_write9_c_full_n) | (1'b0 == H_write8_c_full_n) | (1'b0 == H_write7_c_full_n) | (1'b0 == H_write6_c_full_n) | (1'b0 == H_write5_c_full_n) | (1'b0 == H_write4_c_full_n) | (1'b0 == H_write3_c_full_n) | (1'b0 == H_write2_c_full_n) | (1'b0 == H_write1_c_full_n) | (1'b0 == H_write0_c_full_n) | (1'b0 == H_write15_c_full_n) | (1'b0 == H_write14_c_full_n) | (1'b0 == H_write13_c_full_n) | (1'b0 == H_write12_c_full_n) | (ap_done_reg == 1'b1) | (hyperedge_size_c85_full_n == 1'b0) | (hyperedge_size_c84_full_n == 1'b0) | (hyperedge_size_c83_full_n == 1'b0) | (hyperedge_size_c82_full_n == 1'b0) | (hyperedge_size_c81_full_n == 1'b0) | (hyperedge_size_c80_full_n == 1'b0) | (hyperedge_size_c79_full_n == 1'b0) | (hyperedge_size_c78_full_n == 1'b0) | (hyperedge_size_c77_full_n == 1'b0) | (hyperedge_size_c76_full_n == 1'b0) | (hyperedge_size_c75_full_n == 1'b0) | (hyperedge_size_c74_full_n == 1'b0) | (hyperedge_size_c73_full_n == 1'b0) | (hyperedge_size_c72_full_n == 1'b0) | (hyperedge_size_c71_full_n == 1'b0) | (hyperedge_size_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hyperedge_size_c75_write = 1'b1;
    end else begin
        hyperedge_size_c75_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        hyperedge_size_c76_blk_n = hyperedge_size_c76_full_n;
    end else begin
        hyperedge_size_c76_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (1'b0 == H_write11_c_full_n) | (1'b0 == H_write10_c_full_n) | (1'b0 == H_write9_c_full_n) | (1'b0 == H_write8_c_full_n) | (1'b0 == H_write7_c_full_n) | (1'b0 == H_write6_c_full_n) | (1'b0 == H_write5_c_full_n) | (1'b0 == H_write4_c_full_n) | (1'b0 == H_write3_c_full_n) | (1'b0 == H_write2_c_full_n) | (1'b0 == H_write1_c_full_n) | (1'b0 == H_write0_c_full_n) | (1'b0 == H_write15_c_full_n) | (1'b0 == H_write14_c_full_n) | (1'b0 == H_write13_c_full_n) | (1'b0 == H_write12_c_full_n) | (ap_done_reg == 1'b1) | (hyperedge_size_c85_full_n == 1'b0) | (hyperedge_size_c84_full_n == 1'b0) | (hyperedge_size_c83_full_n == 1'b0) | (hyperedge_size_c82_full_n == 1'b0) | (hyperedge_size_c81_full_n == 1'b0) | (hyperedge_size_c80_full_n == 1'b0) | (hyperedge_size_c79_full_n == 1'b0) | (hyperedge_size_c78_full_n == 1'b0) | (hyperedge_size_c77_full_n == 1'b0) | (hyperedge_size_c76_full_n == 1'b0) | (hyperedge_size_c75_full_n == 1'b0) | (hyperedge_size_c74_full_n == 1'b0) | (hyperedge_size_c73_full_n == 1'b0) | (hyperedge_size_c72_full_n == 1'b0) | (hyperedge_size_c71_full_n == 1'b0) | (hyperedge_size_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hyperedge_size_c76_write = 1'b1;
    end else begin
        hyperedge_size_c76_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        hyperedge_size_c77_blk_n = hyperedge_size_c77_full_n;
    end else begin
        hyperedge_size_c77_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (1'b0 == H_write11_c_full_n) | (1'b0 == H_write10_c_full_n) | (1'b0 == H_write9_c_full_n) | (1'b0 == H_write8_c_full_n) | (1'b0 == H_write7_c_full_n) | (1'b0 == H_write6_c_full_n) | (1'b0 == H_write5_c_full_n) | (1'b0 == H_write4_c_full_n) | (1'b0 == H_write3_c_full_n) | (1'b0 == H_write2_c_full_n) | (1'b0 == H_write1_c_full_n) | (1'b0 == H_write0_c_full_n) | (1'b0 == H_write15_c_full_n) | (1'b0 == H_write14_c_full_n) | (1'b0 == H_write13_c_full_n) | (1'b0 == H_write12_c_full_n) | (ap_done_reg == 1'b1) | (hyperedge_size_c85_full_n == 1'b0) | (hyperedge_size_c84_full_n == 1'b0) | (hyperedge_size_c83_full_n == 1'b0) | (hyperedge_size_c82_full_n == 1'b0) | (hyperedge_size_c81_full_n == 1'b0) | (hyperedge_size_c80_full_n == 1'b0) | (hyperedge_size_c79_full_n == 1'b0) | (hyperedge_size_c78_full_n == 1'b0) | (hyperedge_size_c77_full_n == 1'b0) | (hyperedge_size_c76_full_n == 1'b0) | (hyperedge_size_c75_full_n == 1'b0) | (hyperedge_size_c74_full_n == 1'b0) | (hyperedge_size_c73_full_n == 1'b0) | (hyperedge_size_c72_full_n == 1'b0) | (hyperedge_size_c71_full_n == 1'b0) | (hyperedge_size_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hyperedge_size_c77_write = 1'b1;
    end else begin
        hyperedge_size_c77_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        hyperedge_size_c78_blk_n = hyperedge_size_c78_full_n;
    end else begin
        hyperedge_size_c78_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (1'b0 == H_write11_c_full_n) | (1'b0 == H_write10_c_full_n) | (1'b0 == H_write9_c_full_n) | (1'b0 == H_write8_c_full_n) | (1'b0 == H_write7_c_full_n) | (1'b0 == H_write6_c_full_n) | (1'b0 == H_write5_c_full_n) | (1'b0 == H_write4_c_full_n) | (1'b0 == H_write3_c_full_n) | (1'b0 == H_write2_c_full_n) | (1'b0 == H_write1_c_full_n) | (1'b0 == H_write0_c_full_n) | (1'b0 == H_write15_c_full_n) | (1'b0 == H_write14_c_full_n) | (1'b0 == H_write13_c_full_n) | (1'b0 == H_write12_c_full_n) | (ap_done_reg == 1'b1) | (hyperedge_size_c85_full_n == 1'b0) | (hyperedge_size_c84_full_n == 1'b0) | (hyperedge_size_c83_full_n == 1'b0) | (hyperedge_size_c82_full_n == 1'b0) | (hyperedge_size_c81_full_n == 1'b0) | (hyperedge_size_c80_full_n == 1'b0) | (hyperedge_size_c79_full_n == 1'b0) | (hyperedge_size_c78_full_n == 1'b0) | (hyperedge_size_c77_full_n == 1'b0) | (hyperedge_size_c76_full_n == 1'b0) | (hyperedge_size_c75_full_n == 1'b0) | (hyperedge_size_c74_full_n == 1'b0) | (hyperedge_size_c73_full_n == 1'b0) | (hyperedge_size_c72_full_n == 1'b0) | (hyperedge_size_c71_full_n == 1'b0) | (hyperedge_size_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hyperedge_size_c78_write = 1'b1;
    end else begin
        hyperedge_size_c78_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        hyperedge_size_c79_blk_n = hyperedge_size_c79_full_n;
    end else begin
        hyperedge_size_c79_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (1'b0 == H_write11_c_full_n) | (1'b0 == H_write10_c_full_n) | (1'b0 == H_write9_c_full_n) | (1'b0 == H_write8_c_full_n) | (1'b0 == H_write7_c_full_n) | (1'b0 == H_write6_c_full_n) | (1'b0 == H_write5_c_full_n) | (1'b0 == H_write4_c_full_n) | (1'b0 == H_write3_c_full_n) | (1'b0 == H_write2_c_full_n) | (1'b0 == H_write1_c_full_n) | (1'b0 == H_write0_c_full_n) | (1'b0 == H_write15_c_full_n) | (1'b0 == H_write14_c_full_n) | (1'b0 == H_write13_c_full_n) | (1'b0 == H_write12_c_full_n) | (ap_done_reg == 1'b1) | (hyperedge_size_c85_full_n == 1'b0) | (hyperedge_size_c84_full_n == 1'b0) | (hyperedge_size_c83_full_n == 1'b0) | (hyperedge_size_c82_full_n == 1'b0) | (hyperedge_size_c81_full_n == 1'b0) | (hyperedge_size_c80_full_n == 1'b0) | (hyperedge_size_c79_full_n == 1'b0) | (hyperedge_size_c78_full_n == 1'b0) | (hyperedge_size_c77_full_n == 1'b0) | (hyperedge_size_c76_full_n == 1'b0) | (hyperedge_size_c75_full_n == 1'b0) | (hyperedge_size_c74_full_n == 1'b0) | (hyperedge_size_c73_full_n == 1'b0) | (hyperedge_size_c72_full_n == 1'b0) | (hyperedge_size_c71_full_n == 1'b0) | (hyperedge_size_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hyperedge_size_c79_write = 1'b1;
    end else begin
        hyperedge_size_c79_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        hyperedge_size_c80_blk_n = hyperedge_size_c80_full_n;
    end else begin
        hyperedge_size_c80_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (1'b0 == H_write11_c_full_n) | (1'b0 == H_write10_c_full_n) | (1'b0 == H_write9_c_full_n) | (1'b0 == H_write8_c_full_n) | (1'b0 == H_write7_c_full_n) | (1'b0 == H_write6_c_full_n) | (1'b0 == H_write5_c_full_n) | (1'b0 == H_write4_c_full_n) | (1'b0 == H_write3_c_full_n) | (1'b0 == H_write2_c_full_n) | (1'b0 == H_write1_c_full_n) | (1'b0 == H_write0_c_full_n) | (1'b0 == H_write15_c_full_n) | (1'b0 == H_write14_c_full_n) | (1'b0 == H_write13_c_full_n) | (1'b0 == H_write12_c_full_n) | (ap_done_reg == 1'b1) | (hyperedge_size_c85_full_n == 1'b0) | (hyperedge_size_c84_full_n == 1'b0) | (hyperedge_size_c83_full_n == 1'b0) | (hyperedge_size_c82_full_n == 1'b0) | (hyperedge_size_c81_full_n == 1'b0) | (hyperedge_size_c80_full_n == 1'b0) | (hyperedge_size_c79_full_n == 1'b0) | (hyperedge_size_c78_full_n == 1'b0) | (hyperedge_size_c77_full_n == 1'b0) | (hyperedge_size_c76_full_n == 1'b0) | (hyperedge_size_c75_full_n == 1'b0) | (hyperedge_size_c74_full_n == 1'b0) | (hyperedge_size_c73_full_n == 1'b0) | (hyperedge_size_c72_full_n == 1'b0) | (hyperedge_size_c71_full_n == 1'b0) | (hyperedge_size_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hyperedge_size_c80_write = 1'b1;
    end else begin
        hyperedge_size_c80_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        hyperedge_size_c81_blk_n = hyperedge_size_c81_full_n;
    end else begin
        hyperedge_size_c81_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (1'b0 == H_write11_c_full_n) | (1'b0 == H_write10_c_full_n) | (1'b0 == H_write9_c_full_n) | (1'b0 == H_write8_c_full_n) | (1'b0 == H_write7_c_full_n) | (1'b0 == H_write6_c_full_n) | (1'b0 == H_write5_c_full_n) | (1'b0 == H_write4_c_full_n) | (1'b0 == H_write3_c_full_n) | (1'b0 == H_write2_c_full_n) | (1'b0 == H_write1_c_full_n) | (1'b0 == H_write0_c_full_n) | (1'b0 == H_write15_c_full_n) | (1'b0 == H_write14_c_full_n) | (1'b0 == H_write13_c_full_n) | (1'b0 == H_write12_c_full_n) | (ap_done_reg == 1'b1) | (hyperedge_size_c85_full_n == 1'b0) | (hyperedge_size_c84_full_n == 1'b0) | (hyperedge_size_c83_full_n == 1'b0) | (hyperedge_size_c82_full_n == 1'b0) | (hyperedge_size_c81_full_n == 1'b0) | (hyperedge_size_c80_full_n == 1'b0) | (hyperedge_size_c79_full_n == 1'b0) | (hyperedge_size_c78_full_n == 1'b0) | (hyperedge_size_c77_full_n == 1'b0) | (hyperedge_size_c76_full_n == 1'b0) | (hyperedge_size_c75_full_n == 1'b0) | (hyperedge_size_c74_full_n == 1'b0) | (hyperedge_size_c73_full_n == 1'b0) | (hyperedge_size_c72_full_n == 1'b0) | (hyperedge_size_c71_full_n == 1'b0) | (hyperedge_size_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hyperedge_size_c81_write = 1'b1;
    end else begin
        hyperedge_size_c81_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        hyperedge_size_c82_blk_n = hyperedge_size_c82_full_n;
    end else begin
        hyperedge_size_c82_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (1'b0 == H_write11_c_full_n) | (1'b0 == H_write10_c_full_n) | (1'b0 == H_write9_c_full_n) | (1'b0 == H_write8_c_full_n) | (1'b0 == H_write7_c_full_n) | (1'b0 == H_write6_c_full_n) | (1'b0 == H_write5_c_full_n) | (1'b0 == H_write4_c_full_n) | (1'b0 == H_write3_c_full_n) | (1'b0 == H_write2_c_full_n) | (1'b0 == H_write1_c_full_n) | (1'b0 == H_write0_c_full_n) | (1'b0 == H_write15_c_full_n) | (1'b0 == H_write14_c_full_n) | (1'b0 == H_write13_c_full_n) | (1'b0 == H_write12_c_full_n) | (ap_done_reg == 1'b1) | (hyperedge_size_c85_full_n == 1'b0) | (hyperedge_size_c84_full_n == 1'b0) | (hyperedge_size_c83_full_n == 1'b0) | (hyperedge_size_c82_full_n == 1'b0) | (hyperedge_size_c81_full_n == 1'b0) | (hyperedge_size_c80_full_n == 1'b0) | (hyperedge_size_c79_full_n == 1'b0) | (hyperedge_size_c78_full_n == 1'b0) | (hyperedge_size_c77_full_n == 1'b0) | (hyperedge_size_c76_full_n == 1'b0) | (hyperedge_size_c75_full_n == 1'b0) | (hyperedge_size_c74_full_n == 1'b0) | (hyperedge_size_c73_full_n == 1'b0) | (hyperedge_size_c72_full_n == 1'b0) | (hyperedge_size_c71_full_n == 1'b0) | (hyperedge_size_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hyperedge_size_c82_write = 1'b1;
    end else begin
        hyperedge_size_c82_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        hyperedge_size_c83_blk_n = hyperedge_size_c83_full_n;
    end else begin
        hyperedge_size_c83_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (1'b0 == H_write11_c_full_n) | (1'b0 == H_write10_c_full_n) | (1'b0 == H_write9_c_full_n) | (1'b0 == H_write8_c_full_n) | (1'b0 == H_write7_c_full_n) | (1'b0 == H_write6_c_full_n) | (1'b0 == H_write5_c_full_n) | (1'b0 == H_write4_c_full_n) | (1'b0 == H_write3_c_full_n) | (1'b0 == H_write2_c_full_n) | (1'b0 == H_write1_c_full_n) | (1'b0 == H_write0_c_full_n) | (1'b0 == H_write15_c_full_n) | (1'b0 == H_write14_c_full_n) | (1'b0 == H_write13_c_full_n) | (1'b0 == H_write12_c_full_n) | (ap_done_reg == 1'b1) | (hyperedge_size_c85_full_n == 1'b0) | (hyperedge_size_c84_full_n == 1'b0) | (hyperedge_size_c83_full_n == 1'b0) | (hyperedge_size_c82_full_n == 1'b0) | (hyperedge_size_c81_full_n == 1'b0) | (hyperedge_size_c80_full_n == 1'b0) | (hyperedge_size_c79_full_n == 1'b0) | (hyperedge_size_c78_full_n == 1'b0) | (hyperedge_size_c77_full_n == 1'b0) | (hyperedge_size_c76_full_n == 1'b0) | (hyperedge_size_c75_full_n == 1'b0) | (hyperedge_size_c74_full_n == 1'b0) | (hyperedge_size_c73_full_n == 1'b0) | (hyperedge_size_c72_full_n == 1'b0) | (hyperedge_size_c71_full_n == 1'b0) | (hyperedge_size_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hyperedge_size_c83_write = 1'b1;
    end else begin
        hyperedge_size_c83_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        hyperedge_size_c84_blk_n = hyperedge_size_c84_full_n;
    end else begin
        hyperedge_size_c84_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (1'b0 == H_write11_c_full_n) | (1'b0 == H_write10_c_full_n) | (1'b0 == H_write9_c_full_n) | (1'b0 == H_write8_c_full_n) | (1'b0 == H_write7_c_full_n) | (1'b0 == H_write6_c_full_n) | (1'b0 == H_write5_c_full_n) | (1'b0 == H_write4_c_full_n) | (1'b0 == H_write3_c_full_n) | (1'b0 == H_write2_c_full_n) | (1'b0 == H_write1_c_full_n) | (1'b0 == H_write0_c_full_n) | (1'b0 == H_write15_c_full_n) | (1'b0 == H_write14_c_full_n) | (1'b0 == H_write13_c_full_n) | (1'b0 == H_write12_c_full_n) | (ap_done_reg == 1'b1) | (hyperedge_size_c85_full_n == 1'b0) | (hyperedge_size_c84_full_n == 1'b0) | (hyperedge_size_c83_full_n == 1'b0) | (hyperedge_size_c82_full_n == 1'b0) | (hyperedge_size_c81_full_n == 1'b0) | (hyperedge_size_c80_full_n == 1'b0) | (hyperedge_size_c79_full_n == 1'b0) | (hyperedge_size_c78_full_n == 1'b0) | (hyperedge_size_c77_full_n == 1'b0) | (hyperedge_size_c76_full_n == 1'b0) | (hyperedge_size_c75_full_n == 1'b0) | (hyperedge_size_c74_full_n == 1'b0) | (hyperedge_size_c73_full_n == 1'b0) | (hyperedge_size_c72_full_n == 1'b0) | (hyperedge_size_c71_full_n == 1'b0) | (hyperedge_size_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hyperedge_size_c84_write = 1'b1;
    end else begin
        hyperedge_size_c84_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        hyperedge_size_c85_blk_n = hyperedge_size_c85_full_n;
    end else begin
        hyperedge_size_c85_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (1'b0 == H_write11_c_full_n) | (1'b0 == H_write10_c_full_n) | (1'b0 == H_write9_c_full_n) | (1'b0 == H_write8_c_full_n) | (1'b0 == H_write7_c_full_n) | (1'b0 == H_write6_c_full_n) | (1'b0 == H_write5_c_full_n) | (1'b0 == H_write4_c_full_n) | (1'b0 == H_write3_c_full_n) | (1'b0 == H_write2_c_full_n) | (1'b0 == H_write1_c_full_n) | (1'b0 == H_write0_c_full_n) | (1'b0 == H_write15_c_full_n) | (1'b0 == H_write14_c_full_n) | (1'b0 == H_write13_c_full_n) | (1'b0 == H_write12_c_full_n) | (ap_done_reg == 1'b1) | (hyperedge_size_c85_full_n == 1'b0) | (hyperedge_size_c84_full_n == 1'b0) | (hyperedge_size_c83_full_n == 1'b0) | (hyperedge_size_c82_full_n == 1'b0) | (hyperedge_size_c81_full_n == 1'b0) | (hyperedge_size_c80_full_n == 1'b0) | (hyperedge_size_c79_full_n == 1'b0) | (hyperedge_size_c78_full_n == 1'b0) | (hyperedge_size_c77_full_n == 1'b0) | (hyperedge_size_c76_full_n == 1'b0) | (hyperedge_size_c75_full_n == 1'b0) | (hyperedge_size_c74_full_n == 1'b0) | (hyperedge_size_c73_full_n == 1'b0) | (hyperedge_size_c72_full_n == 1'b0) | (hyperedge_size_c71_full_n == 1'b0) | (hyperedge_size_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hyperedge_size_c85_write = 1'b1;
    end else begin
        hyperedge_size_c85_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        hyperedge_size_c_blk_n = hyperedge_size_c_full_n;
    end else begin
        hyperedge_size_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (1'b0 == H_write11_c_full_n) | (1'b0 == H_write10_c_full_n) | (1'b0 == H_write9_c_full_n) | (1'b0 == H_write8_c_full_n) | (1'b0 == H_write7_c_full_n) | (1'b0 == H_write6_c_full_n) | (1'b0 == H_write5_c_full_n) | (1'b0 == H_write4_c_full_n) | (1'b0 == H_write3_c_full_n) | (1'b0 == H_write2_c_full_n) | (1'b0 == H_write1_c_full_n) | (1'b0 == H_write0_c_full_n) | (1'b0 == H_write15_c_full_n) | (1'b0 == H_write14_c_full_n) | (1'b0 == H_write13_c_full_n) | (1'b0 == H_write12_c_full_n) | (ap_done_reg == 1'b1) | (hyperedge_size_c85_full_n == 1'b0) | (hyperedge_size_c84_full_n == 1'b0) | (hyperedge_size_c83_full_n == 1'b0) | (hyperedge_size_c82_full_n == 1'b0) | (hyperedge_size_c81_full_n == 1'b0) | (hyperedge_size_c80_full_n == 1'b0) | (hyperedge_size_c79_full_n == 1'b0) | (hyperedge_size_c78_full_n == 1'b0) | (hyperedge_size_c77_full_n == 1'b0) | (hyperedge_size_c76_full_n == 1'b0) | (hyperedge_size_c75_full_n == 1'b0) | (hyperedge_size_c74_full_n == 1'b0) | (hyperedge_size_c73_full_n == 1'b0) | (hyperedge_size_c72_full_n == 1'b0) | (hyperedge_size_c71_full_n == 1'b0) | (hyperedge_size_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hyperedge_size_c_write = 1'b1;
    end else begin
        hyperedge_size_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (1'b0 == H_write11_c_full_n) | (1'b0 == H_write10_c_full_n) | (1'b0 == H_write9_c_full_n) | (1'b0 == H_write8_c_full_n) | (1'b0 == H_write7_c_full_n) | (1'b0 == H_write6_c_full_n) | (1'b0 == H_write5_c_full_n) | (1'b0 == H_write4_c_full_n) | (1'b0 == H_write3_c_full_n) | (1'b0 == H_write2_c_full_n) | (1'b0 == H_write1_c_full_n) | (1'b0 == H_write0_c_full_n) | (1'b0 == H_write15_c_full_n) | (1'b0 == H_write14_c_full_n) | (1'b0 == H_write13_c_full_n) | (1'b0 == H_write12_c_full_n) | (ap_done_reg == 1'b1) | (hyperedge_size_c85_full_n == 1'b0) | (hyperedge_size_c84_full_n == 1'b0) | (hyperedge_size_c83_full_n == 1'b0) | (hyperedge_size_c82_full_n == 1'b0) | (hyperedge_size_c81_full_n == 1'b0) | (hyperedge_size_c80_full_n == 1'b0) | (hyperedge_size_c79_full_n == 1'b0) | (hyperedge_size_c78_full_n == 1'b0) | (hyperedge_size_c77_full_n == 1'b0) | (hyperedge_size_c76_full_n == 1'b0) | (hyperedge_size_c75_full_n == 1'b0) | (hyperedge_size_c74_full_n == 1'b0) | (hyperedge_size_c73_full_n == 1'b0) | (hyperedge_size_c72_full_n == 1'b0) | (hyperedge_size_c71_full_n == 1'b0) | (hyperedge_size_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign H_write0_c_din = H_write0;

assign H_write10_c_din = H_write10;

assign H_write11_c_din = H_write11;

assign H_write12_c_din = H_write12;

assign H_write13_c_din = H_write13;

assign H_write14_c_din = H_write14;

assign H_write15_c_din = H_write15;

assign H_write1_c_din = H_write1;

assign H_write2_c_din = H_write2;

assign H_write3_c_din = H_write3;

assign H_write4_c_din = H_write4;

assign H_write5_c_din = H_write5;

assign H_write6_c_din = H_write6;

assign H_write7_c_din = H_write7;

assign H_write8_c_din = H_write8;

assign H_write9_c_din = H_write9;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (1'b0 == H_write11_c_full_n) | (1'b0 == H_write10_c_full_n) | (1'b0 == H_write9_c_full_n) | (1'b0 == H_write8_c_full_n) | (1'b0 == H_write7_c_full_n) | (1'b0 == H_write6_c_full_n) | (1'b0 == H_write5_c_full_n) | (1'b0 == H_write4_c_full_n) | (1'b0 == H_write3_c_full_n) | (1'b0 == H_write2_c_full_n) | (1'b0 == H_write1_c_full_n) | (1'b0 == H_write0_c_full_n) | (1'b0 == H_write15_c_full_n) | (1'b0 == H_write14_c_full_n) | (1'b0 == H_write13_c_full_n) | (1'b0 == H_write12_c_full_n) | (ap_done_reg == 1'b1) | (hyperedge_size_c85_full_n == 1'b0) | (hyperedge_size_c84_full_n == 1'b0) | (hyperedge_size_c83_full_n == 1'b0) | (hyperedge_size_c82_full_n == 1'b0) | (hyperedge_size_c81_full_n == 1'b0) | (hyperedge_size_c80_full_n == 1'b0) | (hyperedge_size_c79_full_n == 1'b0) | (hyperedge_size_c78_full_n == 1'b0) | (hyperedge_size_c77_full_n == 1'b0) | (hyperedge_size_c76_full_n == 1'b0) | (hyperedge_size_c75_full_n == 1'b0) | (hyperedge_size_c74_full_n == 1'b0) | (hyperedge_size_c73_full_n == 1'b0) | (hyperedge_size_c72_full_n == 1'b0) | (hyperedge_size_c71_full_n == 1'b0) | (hyperedge_size_c_full_n == 1'b0));
end

assign ap_ext_blocking_n = (1'b1 & 1'b1);

assign ap_int_blocking_cur_n = (hyperedge_size_c_blk_n & hyperedge_size_c85_blk_n & hyperedge_size_c84_blk_n & hyperedge_size_c83_blk_n & hyperedge_size_c82_blk_n & hyperedge_size_c81_blk_n & hyperedge_size_c80_blk_n & hyperedge_size_c79_blk_n & hyperedge_size_c78_blk_n & hyperedge_size_c77_blk_n & hyperedge_size_c76_blk_n & hyperedge_size_c75_blk_n & hyperedge_size_c74_blk_n & hyperedge_size_c73_blk_n & hyperedge_size_c72_blk_n & hyperedge_size_c71_blk_n & H_write9_c_blk_n & H_write8_c_blk_n & H_write7_c_blk_n & H_write6_c_blk_n & H_write5_c_blk_n & H_write4_c_blk_n & H_write3_c_blk_n & H_write2_c_blk_n & H_write1_c_blk_n & H_write15_c_blk_n & H_write14_c_blk_n & H_write13_c_blk_n & H_write12_c_blk_n & H_write11_c_blk_n & H_write10_c_blk_n & H_write0_c_blk_n);

assign ap_int_blocking_n = (ap_int_blocking_cur_n & 1'b1);

assign ap_ready = internal_ap_ready;

assign ap_str_blocking_n = (1'b1 & 1'b1);

assign hyperedge_size_c71_din = hyperedge_size;

assign hyperedge_size_c72_din = hyperedge_size;

assign hyperedge_size_c73_din = hyperedge_size;

assign hyperedge_size_c74_din = hyperedge_size;

assign hyperedge_size_c75_din = hyperedge_size;

assign hyperedge_size_c76_din = hyperedge_size;

assign hyperedge_size_c77_din = hyperedge_size;

assign hyperedge_size_c78_din = hyperedge_size;

assign hyperedge_size_c79_din = hyperedge_size;

assign hyperedge_size_c80_din = hyperedge_size;

assign hyperedge_size_c81_din = hyperedge_size;

assign hyperedge_size_c82_din = hyperedge_size;

assign hyperedge_size_c83_din = hyperedge_size;

assign hyperedge_size_c84_din = hyperedge_size;

assign hyperedge_size_c85_din = hyperedge_size;

assign hyperedge_size_c_din = hyperedge_size;

assign start_out = real_start;

endmodule //kernel_pr_entry_proc
