// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module kernel_kcore_h2v_kernel_kcore_h2v_pe_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        m_axi_hbm1_AWVALID,
        m_axi_hbm1_AWREADY,
        m_axi_hbm1_AWADDR,
        m_axi_hbm1_AWID,
        m_axi_hbm1_AWLEN,
        m_axi_hbm1_AWSIZE,
        m_axi_hbm1_AWBURST,
        m_axi_hbm1_AWLOCK,
        m_axi_hbm1_AWCACHE,
        m_axi_hbm1_AWPROT,
        m_axi_hbm1_AWQOS,
        m_axi_hbm1_AWREGION,
        m_axi_hbm1_AWUSER,
        m_axi_hbm1_WVALID,
        m_axi_hbm1_WREADY,
        m_axi_hbm1_WDATA,
        m_axi_hbm1_WSTRB,
        m_axi_hbm1_WLAST,
        m_axi_hbm1_WID,
        m_axi_hbm1_WUSER,
        m_axi_hbm1_ARVALID,
        m_axi_hbm1_ARREADY,
        m_axi_hbm1_ARADDR,
        m_axi_hbm1_ARID,
        m_axi_hbm1_ARLEN,
        m_axi_hbm1_ARSIZE,
        m_axi_hbm1_ARBURST,
        m_axi_hbm1_ARLOCK,
        m_axi_hbm1_ARCACHE,
        m_axi_hbm1_ARPROT,
        m_axi_hbm1_ARQOS,
        m_axi_hbm1_ARREGION,
        m_axi_hbm1_ARUSER,
        m_axi_hbm1_RVALID,
        m_axi_hbm1_RREADY,
        m_axi_hbm1_RDATA,
        m_axi_hbm1_RLAST,
        m_axi_hbm1_RID,
        m_axi_hbm1_RFIFONUM,
        m_axi_hbm1_RUSER,
        m_axi_hbm1_RRESP,
        m_axi_hbm1_BVALID,
        m_axi_hbm1_BREADY,
        m_axi_hbm1_BRESP,
        m_axi_hbm1_BID,
        m_axi_hbm1_BUSER,
        V_value,
        H_value,
        vh_offset,
        vh_index,
        to_process_vertex,
        to_process_vertex_count,
        k,
        ap_ext_blocking_n,
        ap_str_blocking_n,
        ap_int_blocking_n
);

parameter    ap_ST_fsm_state1 = 219'd1;
parameter    ap_ST_fsm_state2 = 219'd2;
parameter    ap_ST_fsm_state3 = 219'd4;
parameter    ap_ST_fsm_state4 = 219'd8;
parameter    ap_ST_fsm_state5 = 219'd16;
parameter    ap_ST_fsm_state6 = 219'd32;
parameter    ap_ST_fsm_state7 = 219'd64;
parameter    ap_ST_fsm_state8 = 219'd128;
parameter    ap_ST_fsm_state9 = 219'd256;
parameter    ap_ST_fsm_state10 = 219'd512;
parameter    ap_ST_fsm_state11 = 219'd1024;
parameter    ap_ST_fsm_state12 = 219'd2048;
parameter    ap_ST_fsm_state13 = 219'd4096;
parameter    ap_ST_fsm_state14 = 219'd8192;
parameter    ap_ST_fsm_state15 = 219'd16384;
parameter    ap_ST_fsm_state16 = 219'd32768;
parameter    ap_ST_fsm_state17 = 219'd65536;
parameter    ap_ST_fsm_state18 = 219'd131072;
parameter    ap_ST_fsm_state19 = 219'd262144;
parameter    ap_ST_fsm_state20 = 219'd524288;
parameter    ap_ST_fsm_state21 = 219'd1048576;
parameter    ap_ST_fsm_state22 = 219'd2097152;
parameter    ap_ST_fsm_state23 = 219'd4194304;
parameter    ap_ST_fsm_state24 = 219'd8388608;
parameter    ap_ST_fsm_state25 = 219'd16777216;
parameter    ap_ST_fsm_state26 = 219'd33554432;
parameter    ap_ST_fsm_state27 = 219'd67108864;
parameter    ap_ST_fsm_state28 = 219'd134217728;
parameter    ap_ST_fsm_state29 = 219'd268435456;
parameter    ap_ST_fsm_state30 = 219'd536870912;
parameter    ap_ST_fsm_state31 = 219'd1073741824;
parameter    ap_ST_fsm_state32 = 219'd2147483648;
parameter    ap_ST_fsm_state33 = 219'd4294967296;
parameter    ap_ST_fsm_state34 = 219'd8589934592;
parameter    ap_ST_fsm_state35 = 219'd17179869184;
parameter    ap_ST_fsm_state36 = 219'd34359738368;
parameter    ap_ST_fsm_state37 = 219'd68719476736;
parameter    ap_ST_fsm_state38 = 219'd137438953472;
parameter    ap_ST_fsm_state39 = 219'd274877906944;
parameter    ap_ST_fsm_state40 = 219'd549755813888;
parameter    ap_ST_fsm_state41 = 219'd1099511627776;
parameter    ap_ST_fsm_state42 = 219'd2199023255552;
parameter    ap_ST_fsm_state43 = 219'd4398046511104;
parameter    ap_ST_fsm_state44 = 219'd8796093022208;
parameter    ap_ST_fsm_state45 = 219'd17592186044416;
parameter    ap_ST_fsm_state46 = 219'd35184372088832;
parameter    ap_ST_fsm_state47 = 219'd70368744177664;
parameter    ap_ST_fsm_state48 = 219'd140737488355328;
parameter    ap_ST_fsm_state49 = 219'd281474976710656;
parameter    ap_ST_fsm_state50 = 219'd562949953421312;
parameter    ap_ST_fsm_state51 = 219'd1125899906842624;
parameter    ap_ST_fsm_state52 = 219'd2251799813685248;
parameter    ap_ST_fsm_state53 = 219'd4503599627370496;
parameter    ap_ST_fsm_state54 = 219'd9007199254740992;
parameter    ap_ST_fsm_state55 = 219'd18014398509481984;
parameter    ap_ST_fsm_state56 = 219'd36028797018963968;
parameter    ap_ST_fsm_state57 = 219'd72057594037927936;
parameter    ap_ST_fsm_state58 = 219'd144115188075855872;
parameter    ap_ST_fsm_state59 = 219'd288230376151711744;
parameter    ap_ST_fsm_state60 = 219'd576460752303423488;
parameter    ap_ST_fsm_state61 = 219'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 219'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 219'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 219'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 219'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 219'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 219'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 219'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 219'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 219'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 219'd1180591620717411303424;
parameter    ap_ST_fsm_state72 = 219'd2361183241434822606848;
parameter    ap_ST_fsm_state73 = 219'd4722366482869645213696;
parameter    ap_ST_fsm_state74 = 219'd9444732965739290427392;
parameter    ap_ST_fsm_state75 = 219'd18889465931478580854784;
parameter    ap_ST_fsm_state76 = 219'd37778931862957161709568;
parameter    ap_ST_fsm_state77 = 219'd75557863725914323419136;
parameter    ap_ST_fsm_state78 = 219'd151115727451828646838272;
parameter    ap_ST_fsm_state79 = 219'd302231454903657293676544;
parameter    ap_ST_fsm_state80 = 219'd604462909807314587353088;
parameter    ap_ST_fsm_state81 = 219'd1208925819614629174706176;
parameter    ap_ST_fsm_state82 = 219'd2417851639229258349412352;
parameter    ap_ST_fsm_state83 = 219'd4835703278458516698824704;
parameter    ap_ST_fsm_state84 = 219'd9671406556917033397649408;
parameter    ap_ST_fsm_state85 = 219'd19342813113834066795298816;
parameter    ap_ST_fsm_state86 = 219'd38685626227668133590597632;
parameter    ap_ST_fsm_state87 = 219'd77371252455336267181195264;
parameter    ap_ST_fsm_state88 = 219'd154742504910672534362390528;
parameter    ap_ST_fsm_state89 = 219'd309485009821345068724781056;
parameter    ap_ST_fsm_state90 = 219'd618970019642690137449562112;
parameter    ap_ST_fsm_state91 = 219'd1237940039285380274899124224;
parameter    ap_ST_fsm_state92 = 219'd2475880078570760549798248448;
parameter    ap_ST_fsm_state93 = 219'd4951760157141521099596496896;
parameter    ap_ST_fsm_state94 = 219'd9903520314283042199192993792;
parameter    ap_ST_fsm_state95 = 219'd19807040628566084398385987584;
parameter    ap_ST_fsm_state96 = 219'd39614081257132168796771975168;
parameter    ap_ST_fsm_state97 = 219'd79228162514264337593543950336;
parameter    ap_ST_fsm_state98 = 219'd158456325028528675187087900672;
parameter    ap_ST_fsm_state99 = 219'd316912650057057350374175801344;
parameter    ap_ST_fsm_state100 = 219'd633825300114114700748351602688;
parameter    ap_ST_fsm_state101 = 219'd1267650600228229401496703205376;
parameter    ap_ST_fsm_state102 = 219'd2535301200456458802993406410752;
parameter    ap_ST_fsm_state103 = 219'd5070602400912917605986812821504;
parameter    ap_ST_fsm_state104 = 219'd10141204801825835211973625643008;
parameter    ap_ST_fsm_state105 = 219'd20282409603651670423947251286016;
parameter    ap_ST_fsm_state106 = 219'd40564819207303340847894502572032;
parameter    ap_ST_fsm_state107 = 219'd81129638414606681695789005144064;
parameter    ap_ST_fsm_state108 = 219'd162259276829213363391578010288128;
parameter    ap_ST_fsm_state109 = 219'd324518553658426726783156020576256;
parameter    ap_ST_fsm_state110 = 219'd649037107316853453566312041152512;
parameter    ap_ST_fsm_state111 = 219'd1298074214633706907132624082305024;
parameter    ap_ST_fsm_state112 = 219'd2596148429267413814265248164610048;
parameter    ap_ST_fsm_state113 = 219'd5192296858534827628530496329220096;
parameter    ap_ST_fsm_state114 = 219'd10384593717069655257060992658440192;
parameter    ap_ST_fsm_state115 = 219'd20769187434139310514121985316880384;
parameter    ap_ST_fsm_state116 = 219'd41538374868278621028243970633760768;
parameter    ap_ST_fsm_state117 = 219'd83076749736557242056487941267521536;
parameter    ap_ST_fsm_state118 = 219'd166153499473114484112975882535043072;
parameter    ap_ST_fsm_state119 = 219'd332306998946228968225951765070086144;
parameter    ap_ST_fsm_state120 = 219'd664613997892457936451903530140172288;
parameter    ap_ST_fsm_state121 = 219'd1329227995784915872903807060280344576;
parameter    ap_ST_fsm_state122 = 219'd2658455991569831745807614120560689152;
parameter    ap_ST_fsm_state123 = 219'd5316911983139663491615228241121378304;
parameter    ap_ST_fsm_state124 = 219'd10633823966279326983230456482242756608;
parameter    ap_ST_fsm_state125 = 219'd21267647932558653966460912964485513216;
parameter    ap_ST_fsm_state126 = 219'd42535295865117307932921825928971026432;
parameter    ap_ST_fsm_state127 = 219'd85070591730234615865843651857942052864;
parameter    ap_ST_fsm_state128 = 219'd170141183460469231731687303715884105728;
parameter    ap_ST_fsm_state129 = 219'd340282366920938463463374607431768211456;
parameter    ap_ST_fsm_state130 = 219'd680564733841876926926749214863536422912;
parameter    ap_ST_fsm_state131 = 219'd1361129467683753853853498429727072845824;
parameter    ap_ST_fsm_state132 = 219'd2722258935367507707706996859454145691648;
parameter    ap_ST_fsm_state133 = 219'd5444517870735015415413993718908291383296;
parameter    ap_ST_fsm_state134 = 219'd10889035741470030830827987437816582766592;
parameter    ap_ST_fsm_state135 = 219'd21778071482940061661655974875633165533184;
parameter    ap_ST_fsm_state136 = 219'd43556142965880123323311949751266331066368;
parameter    ap_ST_fsm_state137 = 219'd87112285931760246646623899502532662132736;
parameter    ap_ST_fsm_state138 = 219'd174224571863520493293247799005065324265472;
parameter    ap_ST_fsm_state139 = 219'd348449143727040986586495598010130648530944;
parameter    ap_ST_fsm_state140 = 219'd696898287454081973172991196020261297061888;
parameter    ap_ST_fsm_state141 = 219'd1393796574908163946345982392040522594123776;
parameter    ap_ST_fsm_state142 = 219'd2787593149816327892691964784081045188247552;
parameter    ap_ST_fsm_state143 = 219'd5575186299632655785383929568162090376495104;
parameter    ap_ST_fsm_state144 = 219'd11150372599265311570767859136324180752990208;
parameter    ap_ST_fsm_state145 = 219'd22300745198530623141535718272648361505980416;
parameter    ap_ST_fsm_state146 = 219'd44601490397061246283071436545296723011960832;
parameter    ap_ST_fsm_state147 = 219'd89202980794122492566142873090593446023921664;
parameter    ap_ST_fsm_state148 = 219'd178405961588244985132285746181186892047843328;
parameter    ap_ST_fsm_state149 = 219'd356811923176489970264571492362373784095686656;
parameter    ap_ST_fsm_state150 = 219'd713623846352979940529142984724747568191373312;
parameter    ap_ST_fsm_state151 = 219'd1427247692705959881058285969449495136382746624;
parameter    ap_ST_fsm_state152 = 219'd2854495385411919762116571938898990272765493248;
parameter    ap_ST_fsm_state153 = 219'd5708990770823839524233143877797980545530986496;
parameter    ap_ST_fsm_state154 = 219'd11417981541647679048466287755595961091061972992;
parameter    ap_ST_fsm_state155 = 219'd22835963083295358096932575511191922182123945984;
parameter    ap_ST_fsm_state156 = 219'd45671926166590716193865151022383844364247891968;
parameter    ap_ST_fsm_state157 = 219'd91343852333181432387730302044767688728495783936;
parameter    ap_ST_fsm_state158 = 219'd182687704666362864775460604089535377456991567872;
parameter    ap_ST_fsm_state159 = 219'd365375409332725729550921208179070754913983135744;
parameter    ap_ST_fsm_state160 = 219'd730750818665451459101842416358141509827966271488;
parameter    ap_ST_fsm_state161 = 219'd1461501637330902918203684832716283019655932542976;
parameter    ap_ST_fsm_state162 = 219'd2923003274661805836407369665432566039311865085952;
parameter    ap_ST_fsm_state163 = 219'd5846006549323611672814739330865132078623730171904;
parameter    ap_ST_fsm_state164 = 219'd11692013098647223345629478661730264157247460343808;
parameter    ap_ST_fsm_state165 = 219'd23384026197294446691258957323460528314494920687616;
parameter    ap_ST_fsm_state166 = 219'd46768052394588893382517914646921056628989841375232;
parameter    ap_ST_fsm_state167 = 219'd93536104789177786765035829293842113257979682750464;
parameter    ap_ST_fsm_state168 = 219'd187072209578355573530071658587684226515959365500928;
parameter    ap_ST_fsm_state169 = 219'd374144419156711147060143317175368453031918731001856;
parameter    ap_ST_fsm_state170 = 219'd748288838313422294120286634350736906063837462003712;
parameter    ap_ST_fsm_state171 = 219'd1496577676626844588240573268701473812127674924007424;
parameter    ap_ST_fsm_state172 = 219'd2993155353253689176481146537402947624255349848014848;
parameter    ap_ST_fsm_state173 = 219'd5986310706507378352962293074805895248510699696029696;
parameter    ap_ST_fsm_state174 = 219'd11972621413014756705924586149611790497021399392059392;
parameter    ap_ST_fsm_state175 = 219'd23945242826029513411849172299223580994042798784118784;
parameter    ap_ST_fsm_state176 = 219'd47890485652059026823698344598447161988085597568237568;
parameter    ap_ST_fsm_state177 = 219'd95780971304118053647396689196894323976171195136475136;
parameter    ap_ST_fsm_state178 = 219'd191561942608236107294793378393788647952342390272950272;
parameter    ap_ST_fsm_state179 = 219'd383123885216472214589586756787577295904684780545900544;
parameter    ap_ST_fsm_state180 = 219'd766247770432944429179173513575154591809369561091801088;
parameter    ap_ST_fsm_state181 = 219'd1532495540865888858358347027150309183618739122183602176;
parameter    ap_ST_fsm_state182 = 219'd3064991081731777716716694054300618367237478244367204352;
parameter    ap_ST_fsm_state183 = 219'd6129982163463555433433388108601236734474956488734408704;
parameter    ap_ST_fsm_state184 = 219'd12259964326927110866866776217202473468949912977468817408;
parameter    ap_ST_fsm_state185 = 219'd24519928653854221733733552434404946937899825954937634816;
parameter    ap_ST_fsm_state186 = 219'd49039857307708443467467104868809893875799651909875269632;
parameter    ap_ST_fsm_state187 = 219'd98079714615416886934934209737619787751599303819750539264;
parameter    ap_ST_fsm_state188 = 219'd196159429230833773869868419475239575503198607639501078528;
parameter    ap_ST_fsm_state189 = 219'd392318858461667547739736838950479151006397215279002157056;
parameter    ap_ST_fsm_state190 = 219'd784637716923335095479473677900958302012794430558004314112;
parameter    ap_ST_fsm_state191 = 219'd1569275433846670190958947355801916604025588861116008628224;
parameter    ap_ST_fsm_state192 = 219'd3138550867693340381917894711603833208051177722232017256448;
parameter    ap_ST_fsm_state193 = 219'd6277101735386680763835789423207666416102355444464034512896;
parameter    ap_ST_fsm_state194 = 219'd12554203470773361527671578846415332832204710888928069025792;
parameter    ap_ST_fsm_state195 = 219'd25108406941546723055343157692830665664409421777856138051584;
parameter    ap_ST_fsm_state196 = 219'd50216813883093446110686315385661331328818843555712276103168;
parameter    ap_ST_fsm_state197 = 219'd100433627766186892221372630771322662657637687111424552206336;
parameter    ap_ST_fsm_state198 = 219'd200867255532373784442745261542645325315275374222849104412672;
parameter    ap_ST_fsm_state199 = 219'd401734511064747568885490523085290650630550748445698208825344;
parameter    ap_ST_fsm_state200 = 219'd803469022129495137770981046170581301261101496891396417650688;
parameter    ap_ST_fsm_state201 = 219'd1606938044258990275541962092341162602522202993782792835301376;
parameter    ap_ST_fsm_state202 = 219'd3213876088517980551083924184682325205044405987565585670602752;
parameter    ap_ST_fsm_state203 = 219'd6427752177035961102167848369364650410088811975131171341205504;
parameter    ap_ST_fsm_state204 = 219'd12855504354071922204335696738729300820177623950262342682411008;
parameter    ap_ST_fsm_state205 = 219'd25711008708143844408671393477458601640355247900524685364822016;
parameter    ap_ST_fsm_state206 = 219'd51422017416287688817342786954917203280710495801049370729644032;
parameter    ap_ST_fsm_state207 = 219'd102844034832575377634685573909834406561420991602098741459288064;
parameter    ap_ST_fsm_state208 = 219'd205688069665150755269371147819668813122841983204197482918576128;
parameter    ap_ST_fsm_state209 = 219'd411376139330301510538742295639337626245683966408394965837152256;
parameter    ap_ST_fsm_state210 = 219'd822752278660603021077484591278675252491367932816789931674304512;
parameter    ap_ST_fsm_state211 = 219'd1645504557321206042154969182557350504982735865633579863348609024;
parameter    ap_ST_fsm_state212 = 219'd3291009114642412084309938365114701009965471731267159726697218048;
parameter    ap_ST_fsm_state213 = 219'd6582018229284824168619876730229402019930943462534319453394436096;
parameter    ap_ST_fsm_state214 = 219'd13164036458569648337239753460458804039861886925068638906788872192;
parameter    ap_ST_fsm_state215 = 219'd26328072917139296674479506920917608079723773850137277813577744384;
parameter    ap_ST_fsm_state216 = 219'd52656145834278593348959013841835216159447547700274555627155488768;
parameter    ap_ST_fsm_state217 = 219'd105312291668557186697918027683670432318895095400549111254310977536;
parameter    ap_ST_fsm_state218 = 219'd210624583337114373395836055367340864637790190801098222508621955072;
parameter    ap_ST_fsm_state219 = 219'd421249166674228746791672110734681729275580381602196445017243910144;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   m_axi_hbm1_AWVALID;
input   m_axi_hbm1_AWREADY;
output  [63:0] m_axi_hbm1_AWADDR;
output  [0:0] m_axi_hbm1_AWID;
output  [31:0] m_axi_hbm1_AWLEN;
output  [2:0] m_axi_hbm1_AWSIZE;
output  [1:0] m_axi_hbm1_AWBURST;
output  [1:0] m_axi_hbm1_AWLOCK;
output  [3:0] m_axi_hbm1_AWCACHE;
output  [2:0] m_axi_hbm1_AWPROT;
output  [3:0] m_axi_hbm1_AWQOS;
output  [3:0] m_axi_hbm1_AWREGION;
output  [0:0] m_axi_hbm1_AWUSER;
output   m_axi_hbm1_WVALID;
input   m_axi_hbm1_WREADY;
output  [31:0] m_axi_hbm1_WDATA;
output  [3:0] m_axi_hbm1_WSTRB;
output   m_axi_hbm1_WLAST;
output  [0:0] m_axi_hbm1_WID;
output  [0:0] m_axi_hbm1_WUSER;
output   m_axi_hbm1_ARVALID;
input   m_axi_hbm1_ARREADY;
output  [63:0] m_axi_hbm1_ARADDR;
output  [0:0] m_axi_hbm1_ARID;
output  [31:0] m_axi_hbm1_ARLEN;
output  [2:0] m_axi_hbm1_ARSIZE;
output  [1:0] m_axi_hbm1_ARBURST;
output  [1:0] m_axi_hbm1_ARLOCK;
output  [3:0] m_axi_hbm1_ARCACHE;
output  [2:0] m_axi_hbm1_ARPROT;
output  [3:0] m_axi_hbm1_ARQOS;
output  [3:0] m_axi_hbm1_ARREGION;
output  [0:0] m_axi_hbm1_ARUSER;
input   m_axi_hbm1_RVALID;
output   m_axi_hbm1_RREADY;
input  [31:0] m_axi_hbm1_RDATA;
input   m_axi_hbm1_RLAST;
input  [0:0] m_axi_hbm1_RID;
input  [8:0] m_axi_hbm1_RFIFONUM;
input  [0:0] m_axi_hbm1_RUSER;
input  [1:0] m_axi_hbm1_RRESP;
input   m_axi_hbm1_BVALID;
output   m_axi_hbm1_BREADY;
input  [1:0] m_axi_hbm1_BRESP;
input  [0:0] m_axi_hbm1_BID;
input  [0:0] m_axi_hbm1_BUSER;
input  [63:0] V_value;
input  [63:0] H_value;
input  [63:0] vh_offset;
input  [63:0] vh_index;
input  [63:0] to_process_vertex;
input  [31:0] to_process_vertex_count;
input  [31:0] k;
output   ap_ext_blocking_n;
output   ap_str_blocking_n;
output   ap_int_blocking_n;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_hbm1_AWVALID;
reg m_axi_hbm1_WVALID;
reg m_axi_hbm1_ARVALID;
reg[63:0] m_axi_hbm1_ARADDR;
reg[0:0] m_axi_hbm1_ARID;
reg[31:0] m_axi_hbm1_ARLEN;
reg[2:0] m_axi_hbm1_ARSIZE;
reg[1:0] m_axi_hbm1_ARBURST;
reg[1:0] m_axi_hbm1_ARLOCK;
reg[3:0] m_axi_hbm1_ARCACHE;
reg[2:0] m_axi_hbm1_ARPROT;
reg[3:0] m_axi_hbm1_ARQOS;
reg[3:0] m_axi_hbm1_ARREGION;
reg[0:0] m_axi_hbm1_ARUSER;
reg m_axi_hbm1_RREADY;
reg m_axi_hbm1_BREADY;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [218:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    hbm1_blk_n_AR;
wire    ap_CS_fsm_state3;
reg    hbm1_blk_n_R;
wire    ap_CS_fsm_state73;
wire    ap_CS_fsm_state75;
wire    ap_CS_fsm_state145;
wire    ap_CS_fsm_state76;
wire    ap_CS_fsm_state146;
wire    ap_CS_fsm_state77;
wire    ap_CS_fsm_state147;
reg    hbm1_blk_n_AW;
wire    ap_CS_fsm_state150;
reg    hbm1_blk_n_W;
wire    ap_CS_fsm_state151;
reg    hbm1_blk_n_B;
wire    ap_CS_fsm_state219;
wire   [31:0] origin_value_43_fu_201_p2;
reg   [31:0] origin_value_43_reg_454;
wire  signed [62:0] sext_ln42_fu_217_p1;
reg  signed [62:0] sext_ln42_reg_459;
reg   [63:0] hbm1_addr_reg_467;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln42_fu_229_p2;
reg   [31:0] hbm1_addr_read_reg_473;
reg   [27:0] tmp_reg_478;
reg  signed [61:0] trunc_ln23_reg_483;
wire    ap_CS_fsm_state74;
reg   [63:0] hbm1_addr_3_reg_489;
reg   [63:0] hbm1_addr_2_reg_502;
reg   [31:0] begin_reg_508;
reg   [31:0] end_reg_514;
reg   [61:0] trunc_ln21_reg_519;
reg   [31:0] origin_value_reg_524;
wire   [31:0] origin_value_45_fu_404_p3;
reg   [31:0] origin_value_45_reg_529;
wire    grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_ap_start;
wire    grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_ap_done;
wire    grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_ap_idle;
wire    grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_ap_ready;
wire    grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_AWVALID;
wire   [63:0] grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_AWADDR;
wire   [0:0] grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_AWID;
wire   [31:0] grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_AWLEN;
wire   [2:0] grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_AWSIZE;
wire   [1:0] grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_AWBURST;
wire   [1:0] grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_AWLOCK;
wire   [3:0] grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_AWCACHE;
wire   [2:0] grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_AWPROT;
wire   [3:0] grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_AWQOS;
wire   [3:0] grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_AWREGION;
wire   [0:0] grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_AWUSER;
wire    grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_WVALID;
wire   [31:0] grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_WDATA;
wire   [3:0] grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_WSTRB;
wire    grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_WLAST;
wire   [0:0] grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_WID;
wire   [0:0] grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_WUSER;
wire    grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_ARVALID;
wire   [63:0] grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_ARADDR;
wire   [0:0] grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_ARID;
wire   [31:0] grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_ARLEN;
wire   [2:0] grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_ARSIZE;
wire   [1:0] grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_ARBURST;
wire   [1:0] grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_ARLOCK;
wire   [3:0] grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_ARCACHE;
wire   [2:0] grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_ARPROT;
wire   [3:0] grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_ARQOS;
wire   [3:0] grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_ARREGION;
wire   [0:0] grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_ARUSER;
wire    grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_RREADY;
wire    grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_BREADY;
wire   [31:0] grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_h_active_count_out;
wire    grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_h_active_count_out_ap_vld;
wire    grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_ap_ext_blocking_n;
wire    grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_ap_str_blocking_n;
wire    grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_ap_int_blocking_n;
reg    grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_ap_start_reg;
reg   [218:0] ap_NS_fsm;
wire    ap_NS_fsm_state148;
wire    ap_CS_fsm_state149;
wire    ap_CS_fsm_state148;
wire  signed [63:0] sext_ln587_44_fu_249_p1;
wire  signed [63:0] sext_ln587_15_fu_326_p1;
wire  signed [63:0] sext_ln587_fu_336_p1;
wire  signed [63:0] sext_ln587_46_fu_355_p1;
reg   [31:0] i_fu_82;
wire   [31:0] add_ln42_fu_234_p2;
reg    ap_block_state1;
wire   [61:0] trunc_ln_fu_207_p4;
wire   [62:0] zext_ln42_fu_240_p1;
wire   [62:0] add_ln587_fu_244_p2;
wire   [29:0] shl_ln_fu_274_p3;
wire   [63:0] zext_ln587_fu_281_p1;
wire   [63:0] add_ln587_43_fu_285_p2;
wire   [33:0] shl_ln587_s_fu_300_p3;
wire   [63:0] zext_ln587_15_fu_307_p1;
wire   [63:0] add_ln587_45_fu_311_p2;
wire   [61:0] trunc_ln587_s_fu_316_p4;
wire  signed [62:0] sext_ln587_45_fu_339_p1;
wire   [62:0] add_ln587_44_fu_349_p2;
wire   [33:0] shl_ln10_fu_365_p3;
wire   [63:0] zext_ln21_fu_372_p1;
wire   [63:0] add_ln21_fu_376_p2;
wire   [31:0] origin_value_44_fu_394_p2;
wire   [0:0] icmp_ln25_fu_399_p2;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
wire    ap_ST_fsm_state50_blk;
wire    ap_ST_fsm_state51_blk;
wire    ap_ST_fsm_state52_blk;
wire    ap_ST_fsm_state53_blk;
wire    ap_ST_fsm_state54_blk;
wire    ap_ST_fsm_state55_blk;
wire    ap_ST_fsm_state56_blk;
wire    ap_ST_fsm_state57_blk;
wire    ap_ST_fsm_state58_blk;
wire    ap_ST_fsm_state59_blk;
wire    ap_ST_fsm_state60_blk;
wire    ap_ST_fsm_state61_blk;
wire    ap_ST_fsm_state62_blk;
wire    ap_ST_fsm_state63_blk;
wire    ap_ST_fsm_state64_blk;
wire    ap_ST_fsm_state65_blk;
wire    ap_ST_fsm_state66_blk;
wire    ap_ST_fsm_state67_blk;
wire    ap_ST_fsm_state68_blk;
wire    ap_ST_fsm_state69_blk;
wire    ap_ST_fsm_state70_blk;
wire    ap_ST_fsm_state71_blk;
wire    ap_ST_fsm_state72_blk;
reg    ap_ST_fsm_state73_blk;
wire    ap_ST_fsm_state74_blk;
reg    ap_ST_fsm_state75_blk;
reg    ap_ST_fsm_state76_blk;
reg    ap_ST_fsm_state77_blk;
wire    ap_ST_fsm_state78_blk;
wire    ap_ST_fsm_state79_blk;
wire    ap_ST_fsm_state80_blk;
wire    ap_ST_fsm_state81_blk;
wire    ap_ST_fsm_state82_blk;
wire    ap_ST_fsm_state83_blk;
wire    ap_ST_fsm_state84_blk;
wire    ap_ST_fsm_state85_blk;
wire    ap_ST_fsm_state86_blk;
wire    ap_ST_fsm_state87_blk;
wire    ap_ST_fsm_state88_blk;
wire    ap_ST_fsm_state89_blk;
wire    ap_ST_fsm_state90_blk;
wire    ap_ST_fsm_state91_blk;
wire    ap_ST_fsm_state92_blk;
wire    ap_ST_fsm_state93_blk;
wire    ap_ST_fsm_state94_blk;
wire    ap_ST_fsm_state95_blk;
wire    ap_ST_fsm_state96_blk;
wire    ap_ST_fsm_state97_blk;
wire    ap_ST_fsm_state98_blk;
wire    ap_ST_fsm_state99_blk;
wire    ap_ST_fsm_state100_blk;
wire    ap_ST_fsm_state101_blk;
wire    ap_ST_fsm_state102_blk;
wire    ap_ST_fsm_state103_blk;
wire    ap_ST_fsm_state104_blk;
wire    ap_ST_fsm_state105_blk;
wire    ap_ST_fsm_state106_blk;
wire    ap_ST_fsm_state107_blk;
wire    ap_ST_fsm_state108_blk;
wire    ap_ST_fsm_state109_blk;
wire    ap_ST_fsm_state110_blk;
wire    ap_ST_fsm_state111_blk;
wire    ap_ST_fsm_state112_blk;
wire    ap_ST_fsm_state113_blk;
wire    ap_ST_fsm_state114_blk;
wire    ap_ST_fsm_state115_blk;
wire    ap_ST_fsm_state116_blk;
wire    ap_ST_fsm_state117_blk;
wire    ap_ST_fsm_state118_blk;
wire    ap_ST_fsm_state119_blk;
wire    ap_ST_fsm_state120_blk;
wire    ap_ST_fsm_state121_blk;
wire    ap_ST_fsm_state122_blk;
wire    ap_ST_fsm_state123_blk;
wire    ap_ST_fsm_state124_blk;
wire    ap_ST_fsm_state125_blk;
wire    ap_ST_fsm_state126_blk;
wire    ap_ST_fsm_state127_blk;
wire    ap_ST_fsm_state128_blk;
wire    ap_ST_fsm_state129_blk;
wire    ap_ST_fsm_state130_blk;
wire    ap_ST_fsm_state131_blk;
wire    ap_ST_fsm_state132_blk;
wire    ap_ST_fsm_state133_blk;
wire    ap_ST_fsm_state134_blk;
wire    ap_ST_fsm_state135_blk;
wire    ap_ST_fsm_state136_blk;
wire    ap_ST_fsm_state137_blk;
wire    ap_ST_fsm_state138_blk;
wire    ap_ST_fsm_state139_blk;
wire    ap_ST_fsm_state140_blk;
wire    ap_ST_fsm_state141_blk;
wire    ap_ST_fsm_state142_blk;
wire    ap_ST_fsm_state143_blk;
wire    ap_ST_fsm_state144_blk;
reg    ap_ST_fsm_state145_blk;
reg    ap_ST_fsm_state146_blk;
reg    ap_ST_fsm_state147_blk;
wire    ap_ST_fsm_state148_blk;
reg    ap_ST_fsm_state149_blk;
reg    ap_ST_fsm_state150_blk;
reg    ap_ST_fsm_state151_blk;
wire    ap_ST_fsm_state152_blk;
wire    ap_ST_fsm_state153_blk;
wire    ap_ST_fsm_state154_blk;
wire    ap_ST_fsm_state155_blk;
wire    ap_ST_fsm_state156_blk;
wire    ap_ST_fsm_state157_blk;
wire    ap_ST_fsm_state158_blk;
wire    ap_ST_fsm_state159_blk;
wire    ap_ST_fsm_state160_blk;
wire    ap_ST_fsm_state161_blk;
wire    ap_ST_fsm_state162_blk;
wire    ap_ST_fsm_state163_blk;
wire    ap_ST_fsm_state164_blk;
wire    ap_ST_fsm_state165_blk;
wire    ap_ST_fsm_state166_blk;
wire    ap_ST_fsm_state167_blk;
wire    ap_ST_fsm_state168_blk;
wire    ap_ST_fsm_state169_blk;
wire    ap_ST_fsm_state170_blk;
wire    ap_ST_fsm_state171_blk;
wire    ap_ST_fsm_state172_blk;
wire    ap_ST_fsm_state173_blk;
wire    ap_ST_fsm_state174_blk;
wire    ap_ST_fsm_state175_blk;
wire    ap_ST_fsm_state176_blk;
wire    ap_ST_fsm_state177_blk;
wire    ap_ST_fsm_state178_blk;
wire    ap_ST_fsm_state179_blk;
wire    ap_ST_fsm_state180_blk;
wire    ap_ST_fsm_state181_blk;
wire    ap_ST_fsm_state182_blk;
wire    ap_ST_fsm_state183_blk;
wire    ap_ST_fsm_state184_blk;
wire    ap_ST_fsm_state185_blk;
wire    ap_ST_fsm_state186_blk;
wire    ap_ST_fsm_state187_blk;
wire    ap_ST_fsm_state188_blk;
wire    ap_ST_fsm_state189_blk;
wire    ap_ST_fsm_state190_blk;
wire    ap_ST_fsm_state191_blk;
wire    ap_ST_fsm_state192_blk;
wire    ap_ST_fsm_state193_blk;
wire    ap_ST_fsm_state194_blk;
wire    ap_ST_fsm_state195_blk;
wire    ap_ST_fsm_state196_blk;
wire    ap_ST_fsm_state197_blk;
wire    ap_ST_fsm_state198_blk;
wire    ap_ST_fsm_state199_blk;
wire    ap_ST_fsm_state200_blk;
wire    ap_ST_fsm_state201_blk;
wire    ap_ST_fsm_state202_blk;
wire    ap_ST_fsm_state203_blk;
wire    ap_ST_fsm_state204_blk;
wire    ap_ST_fsm_state205_blk;
wire    ap_ST_fsm_state206_blk;
wire    ap_ST_fsm_state207_blk;
wire    ap_ST_fsm_state208_blk;
wire    ap_ST_fsm_state209_blk;
wire    ap_ST_fsm_state210_blk;
wire    ap_ST_fsm_state211_blk;
wire    ap_ST_fsm_state212_blk;
wire    ap_ST_fsm_state213_blk;
wire    ap_ST_fsm_state214_blk;
wire    ap_ST_fsm_state215_blk;
wire    ap_ST_fsm_state216_blk;
wire    ap_ST_fsm_state217_blk;
wire    ap_ST_fsm_state218_blk;
reg    ap_ST_fsm_state219_blk;
wire    ap_ext_blocking_cur_n;
reg    ap_ext_blocking_sub_n;
reg    ap_wait_0;
reg    ap_sub_ext_blocking_0;
reg    ap_str_blocking_sub_n;
reg    ap_sub_str_blocking_0;
reg    ap_int_blocking_sub_n;
reg    ap_sub_int_blocking_0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 219'd1;
#0 grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_ap_start_reg = 1'b0;
end

kernel_kcore_h2v_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1 grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_ap_start),
    .ap_done(grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_ap_done),
    .ap_idle(grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_ap_idle),
    .ap_ready(grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_ap_ready),
    .m_axi_hbm1_AWVALID(grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_AWVALID),
    .m_axi_hbm1_AWREADY(1'b0),
    .m_axi_hbm1_AWADDR(grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_AWADDR),
    .m_axi_hbm1_AWID(grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_AWID),
    .m_axi_hbm1_AWLEN(grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_AWLEN),
    .m_axi_hbm1_AWSIZE(grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_AWSIZE),
    .m_axi_hbm1_AWBURST(grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_AWBURST),
    .m_axi_hbm1_AWLOCK(grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_AWLOCK),
    .m_axi_hbm1_AWCACHE(grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_AWCACHE),
    .m_axi_hbm1_AWPROT(grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_AWPROT),
    .m_axi_hbm1_AWQOS(grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_AWQOS),
    .m_axi_hbm1_AWREGION(grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_AWREGION),
    .m_axi_hbm1_AWUSER(grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_AWUSER),
    .m_axi_hbm1_WVALID(grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_WVALID),
    .m_axi_hbm1_WREADY(1'b0),
    .m_axi_hbm1_WDATA(grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_WDATA),
    .m_axi_hbm1_WSTRB(grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_WSTRB),
    .m_axi_hbm1_WLAST(grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_WLAST),
    .m_axi_hbm1_WID(grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_WID),
    .m_axi_hbm1_WUSER(grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_WUSER),
    .m_axi_hbm1_ARVALID(grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_ARVALID),
    .m_axi_hbm1_ARREADY(m_axi_hbm1_ARREADY),
    .m_axi_hbm1_ARADDR(grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_ARADDR),
    .m_axi_hbm1_ARID(grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_ARID),
    .m_axi_hbm1_ARLEN(grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_ARLEN),
    .m_axi_hbm1_ARSIZE(grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_ARSIZE),
    .m_axi_hbm1_ARBURST(grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_ARBURST),
    .m_axi_hbm1_ARLOCK(grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_ARLOCK),
    .m_axi_hbm1_ARCACHE(grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_ARCACHE),
    .m_axi_hbm1_ARPROT(grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_ARPROT),
    .m_axi_hbm1_ARQOS(grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_ARQOS),
    .m_axi_hbm1_ARREGION(grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_ARREGION),
    .m_axi_hbm1_ARUSER(grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_ARUSER),
    .m_axi_hbm1_RVALID(m_axi_hbm1_RVALID),
    .m_axi_hbm1_RREADY(grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_RREADY),
    .m_axi_hbm1_RDATA(m_axi_hbm1_RDATA),
    .m_axi_hbm1_RLAST(m_axi_hbm1_RLAST),
    .m_axi_hbm1_RID(m_axi_hbm1_RID),
    .m_axi_hbm1_RFIFONUM(m_axi_hbm1_RFIFONUM),
    .m_axi_hbm1_RUSER(m_axi_hbm1_RUSER),
    .m_axi_hbm1_RRESP(m_axi_hbm1_RRESP),
    .m_axi_hbm1_BVALID(1'b0),
    .m_axi_hbm1_BREADY(grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_BREADY),
    .m_axi_hbm1_BRESP(2'd0),
    .m_axi_hbm1_BID(1'd0),
    .m_axi_hbm1_BUSER(1'd0),
    .zext_ln21(begin_reg_508),
    .zext_ln21_15(end_reg_514),
    .sext_ln21(trunc_ln21_reg_519),
    .H_value(H_value),
    .h_active_count_out(grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_h_active_count_out),
    .h_active_count_out_ap_vld(grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_h_active_count_out_ap_vld),
    .ap_ext_blocking_n(grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_ap_ext_blocking_n),
    .ap_str_blocking_n(grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_ap_str_blocking_n),
    .ap_int_blocking_n(grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_ap_int_blocking_n)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln42_fu_229_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state148) & (1'b1 == ap_CS_fsm_state147))) begin
            grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_ap_start_reg <= 1'b1;
        end else if ((grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_ap_ready == 1'b1)) begin
            grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_82 <= 32'd0;
    end else if (((icmp_ln42_fu_229_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i_fu_82 <= add_ln42_fu_234_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state145)) begin
        begin_reg_508 <= m_axi_hbm1_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state146)) begin
        end_reg_514 <= m_axi_hbm1_RDATA;
        trunc_ln21_reg_519 <= {{add_ln21_fu_376_p2[63:2]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state75)) begin
        hbm1_addr_2_reg_502 <= sext_ln587_46_fu_355_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state74)) begin
        hbm1_addr_3_reg_489 <= sext_ln587_15_fu_326_p1;
        trunc_ln23_reg_483 <= {{add_ln587_43_fu_285_p2[63:2]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state73)) begin
        hbm1_addr_read_reg_473 <= m_axi_hbm1_RDATA;
        tmp_reg_478 <= {{m_axi_hbm1_RDATA[31:4]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln42_fu_229_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        hbm1_addr_reg_467 <= sext_ln587_44_fu_249_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        origin_value_43_reg_454 <= origin_value_43_fu_201_p2;
        sext_ln42_reg_459 <= sext_ln42_fu_217_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state150)) begin
        origin_value_45_reg_529 <= origin_value_45_fu_404_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state147)) begin
        origin_value_reg_524 <= m_axi_hbm1_RDATA;
    end
end

assign ap_ST_fsm_state100_blk = 1'b0;

assign ap_ST_fsm_state101_blk = 1'b0;

assign ap_ST_fsm_state102_blk = 1'b0;

assign ap_ST_fsm_state103_blk = 1'b0;

assign ap_ST_fsm_state104_blk = 1'b0;

assign ap_ST_fsm_state105_blk = 1'b0;

assign ap_ST_fsm_state106_blk = 1'b0;

assign ap_ST_fsm_state107_blk = 1'b0;

assign ap_ST_fsm_state108_blk = 1'b0;

assign ap_ST_fsm_state109_blk = 1'b0;

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state110_blk = 1'b0;

assign ap_ST_fsm_state111_blk = 1'b0;

assign ap_ST_fsm_state112_blk = 1'b0;

assign ap_ST_fsm_state113_blk = 1'b0;

assign ap_ST_fsm_state114_blk = 1'b0;

assign ap_ST_fsm_state115_blk = 1'b0;

assign ap_ST_fsm_state116_blk = 1'b0;

assign ap_ST_fsm_state117_blk = 1'b0;

assign ap_ST_fsm_state118_blk = 1'b0;

assign ap_ST_fsm_state119_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state120_blk = 1'b0;

assign ap_ST_fsm_state121_blk = 1'b0;

assign ap_ST_fsm_state122_blk = 1'b0;

assign ap_ST_fsm_state123_blk = 1'b0;

assign ap_ST_fsm_state124_blk = 1'b0;

assign ap_ST_fsm_state125_blk = 1'b0;

assign ap_ST_fsm_state126_blk = 1'b0;

assign ap_ST_fsm_state127_blk = 1'b0;

assign ap_ST_fsm_state128_blk = 1'b0;

assign ap_ST_fsm_state129_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state130_blk = 1'b0;

assign ap_ST_fsm_state131_blk = 1'b0;

assign ap_ST_fsm_state132_blk = 1'b0;

assign ap_ST_fsm_state133_blk = 1'b0;

assign ap_ST_fsm_state134_blk = 1'b0;

assign ap_ST_fsm_state135_blk = 1'b0;

assign ap_ST_fsm_state136_blk = 1'b0;

assign ap_ST_fsm_state137_blk = 1'b0;

assign ap_ST_fsm_state138_blk = 1'b0;

assign ap_ST_fsm_state139_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state140_blk = 1'b0;

assign ap_ST_fsm_state141_blk = 1'b0;

assign ap_ST_fsm_state142_blk = 1'b0;

assign ap_ST_fsm_state143_blk = 1'b0;

assign ap_ST_fsm_state144_blk = 1'b0;

always @ (*) begin
    if ((m_axi_hbm1_RVALID == 1'b0)) begin
        ap_ST_fsm_state145_blk = 1'b1;
    end else begin
        ap_ST_fsm_state145_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_hbm1_RVALID == 1'b0)) begin
        ap_ST_fsm_state146_blk = 1'b1;
    end else begin
        ap_ST_fsm_state146_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_hbm1_RVALID == 1'b0)) begin
        ap_ST_fsm_state147_blk = 1'b1;
    end else begin
        ap_ST_fsm_state147_blk = 1'b0;
    end
end

assign ap_ST_fsm_state148_blk = 1'b0;

always @ (*) begin
    if ((grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_ap_done == 1'b0)) begin
        ap_ST_fsm_state149_blk = 1'b1;
    end else begin
        ap_ST_fsm_state149_blk = 1'b0;
    end
end

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((m_axi_hbm1_AWREADY == 1'b0)) begin
        ap_ST_fsm_state150_blk = 1'b1;
    end else begin
        ap_ST_fsm_state150_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_hbm1_WREADY == 1'b0)) begin
        ap_ST_fsm_state151_blk = 1'b1;
    end else begin
        ap_ST_fsm_state151_blk = 1'b0;
    end
end

assign ap_ST_fsm_state152_blk = 1'b0;

assign ap_ST_fsm_state153_blk = 1'b0;

assign ap_ST_fsm_state154_blk = 1'b0;

assign ap_ST_fsm_state155_blk = 1'b0;

assign ap_ST_fsm_state156_blk = 1'b0;

assign ap_ST_fsm_state157_blk = 1'b0;

assign ap_ST_fsm_state158_blk = 1'b0;

assign ap_ST_fsm_state159_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state160_blk = 1'b0;

assign ap_ST_fsm_state161_blk = 1'b0;

assign ap_ST_fsm_state162_blk = 1'b0;

assign ap_ST_fsm_state163_blk = 1'b0;

assign ap_ST_fsm_state164_blk = 1'b0;

assign ap_ST_fsm_state165_blk = 1'b0;

assign ap_ST_fsm_state166_blk = 1'b0;

assign ap_ST_fsm_state167_blk = 1'b0;

assign ap_ST_fsm_state168_blk = 1'b0;

assign ap_ST_fsm_state169_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state170_blk = 1'b0;

assign ap_ST_fsm_state171_blk = 1'b0;

assign ap_ST_fsm_state172_blk = 1'b0;

assign ap_ST_fsm_state173_blk = 1'b0;

assign ap_ST_fsm_state174_blk = 1'b0;

assign ap_ST_fsm_state175_blk = 1'b0;

assign ap_ST_fsm_state176_blk = 1'b0;

assign ap_ST_fsm_state177_blk = 1'b0;

assign ap_ST_fsm_state178_blk = 1'b0;

assign ap_ST_fsm_state179_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state180_blk = 1'b0;

assign ap_ST_fsm_state181_blk = 1'b0;

assign ap_ST_fsm_state182_blk = 1'b0;

assign ap_ST_fsm_state183_blk = 1'b0;

assign ap_ST_fsm_state184_blk = 1'b0;

assign ap_ST_fsm_state185_blk = 1'b0;

assign ap_ST_fsm_state186_blk = 1'b0;

assign ap_ST_fsm_state187_blk = 1'b0;

assign ap_ST_fsm_state188_blk = 1'b0;

assign ap_ST_fsm_state189_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state190_blk = 1'b0;

assign ap_ST_fsm_state191_blk = 1'b0;

assign ap_ST_fsm_state192_blk = 1'b0;

assign ap_ST_fsm_state193_blk = 1'b0;

assign ap_ST_fsm_state194_blk = 1'b0;

assign ap_ST_fsm_state195_blk = 1'b0;

assign ap_ST_fsm_state196_blk = 1'b0;

assign ap_ST_fsm_state197_blk = 1'b0;

assign ap_ST_fsm_state198_blk = 1'b0;

assign ap_ST_fsm_state199_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state200_blk = 1'b0;

assign ap_ST_fsm_state201_blk = 1'b0;

assign ap_ST_fsm_state202_blk = 1'b0;

assign ap_ST_fsm_state203_blk = 1'b0;

assign ap_ST_fsm_state204_blk = 1'b0;

assign ap_ST_fsm_state205_blk = 1'b0;

assign ap_ST_fsm_state206_blk = 1'b0;

assign ap_ST_fsm_state207_blk = 1'b0;

assign ap_ST_fsm_state208_blk = 1'b0;

assign ap_ST_fsm_state209_blk = 1'b0;

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state210_blk = 1'b0;

assign ap_ST_fsm_state211_blk = 1'b0;

assign ap_ST_fsm_state212_blk = 1'b0;

assign ap_ST_fsm_state213_blk = 1'b0;

assign ap_ST_fsm_state214_blk = 1'b0;

assign ap_ST_fsm_state215_blk = 1'b0;

assign ap_ST_fsm_state216_blk = 1'b0;

assign ap_ST_fsm_state217_blk = 1'b0;

assign ap_ST_fsm_state218_blk = 1'b0;

always @ (*) begin
    if ((m_axi_hbm1_BVALID == 1'b0)) begin
        ap_ST_fsm_state219_blk = 1'b1;
    end else begin
        ap_ST_fsm_state219_blk = 1'b0;
    end
end

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

always @ (*) begin
    if ((m_axi_hbm1_ARREADY == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state50_blk = 1'b0;

assign ap_ST_fsm_state51_blk = 1'b0;

assign ap_ST_fsm_state52_blk = 1'b0;

assign ap_ST_fsm_state53_blk = 1'b0;

assign ap_ST_fsm_state54_blk = 1'b0;

assign ap_ST_fsm_state55_blk = 1'b0;

assign ap_ST_fsm_state56_blk = 1'b0;

assign ap_ST_fsm_state57_blk = 1'b0;

assign ap_ST_fsm_state58_blk = 1'b0;

assign ap_ST_fsm_state59_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state60_blk = 1'b0;

assign ap_ST_fsm_state61_blk = 1'b0;

assign ap_ST_fsm_state62_blk = 1'b0;

assign ap_ST_fsm_state63_blk = 1'b0;

assign ap_ST_fsm_state64_blk = 1'b0;

assign ap_ST_fsm_state65_blk = 1'b0;

assign ap_ST_fsm_state66_blk = 1'b0;

assign ap_ST_fsm_state67_blk = 1'b0;

assign ap_ST_fsm_state68_blk = 1'b0;

assign ap_ST_fsm_state69_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state70_blk = 1'b0;

assign ap_ST_fsm_state71_blk = 1'b0;

assign ap_ST_fsm_state72_blk = 1'b0;

always @ (*) begin
    if ((m_axi_hbm1_RVALID == 1'b0)) begin
        ap_ST_fsm_state73_blk = 1'b1;
    end else begin
        ap_ST_fsm_state73_blk = 1'b0;
    end
end

assign ap_ST_fsm_state74_blk = 1'b0;

always @ (*) begin
    if ((m_axi_hbm1_ARREADY == 1'b0)) begin
        ap_ST_fsm_state75_blk = 1'b1;
    end else begin
        ap_ST_fsm_state75_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_hbm1_ARREADY == 1'b0)) begin
        ap_ST_fsm_state76_blk = 1'b1;
    end else begin
        ap_ST_fsm_state76_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_hbm1_ARREADY == 1'b0)) begin
        ap_ST_fsm_state77_blk = 1'b1;
    end else begin
        ap_ST_fsm_state77_blk = 1'b0;
    end
end

assign ap_ST_fsm_state78_blk = 1'b0;

assign ap_ST_fsm_state79_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state80_blk = 1'b0;

assign ap_ST_fsm_state81_blk = 1'b0;

assign ap_ST_fsm_state82_blk = 1'b0;

assign ap_ST_fsm_state83_blk = 1'b0;

assign ap_ST_fsm_state84_blk = 1'b0;

assign ap_ST_fsm_state85_blk = 1'b0;

assign ap_ST_fsm_state86_blk = 1'b0;

assign ap_ST_fsm_state87_blk = 1'b0;

assign ap_ST_fsm_state88_blk = 1'b0;

assign ap_ST_fsm_state89_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state90_blk = 1'b0;

assign ap_ST_fsm_state91_blk = 1'b0;

assign ap_ST_fsm_state92_blk = 1'b0;

assign ap_ST_fsm_state93_blk = 1'b0;

assign ap_ST_fsm_state94_blk = 1'b0;

assign ap_ST_fsm_state95_blk = 1'b0;

assign ap_ST_fsm_state96_blk = 1'b0;

assign ap_ST_fsm_state97_blk = 1'b0;

assign ap_ST_fsm_state98_blk = 1'b0;

assign ap_ST_fsm_state99_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln42_fu_229_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_wait_0 & ap_sub_ext_blocking_0) == 1'b1)) begin
        ap_ext_blocking_sub_n = 1'b0;
    end else begin
        ap_ext_blocking_sub_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_wait_0 & ap_sub_int_blocking_0) == 1'b1)) begin
        ap_int_blocking_sub_n = 1'b0;
    end else begin
        ap_int_blocking_sub_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln42_fu_229_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_wait_0 & ap_sub_str_blocking_0) == 1'b1)) begin
        ap_str_blocking_sub_n = 1'b0;
    end else begin
        ap_str_blocking_sub_n = 1'b1;
    end
end

always @ (*) begin
    if ((grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_ap_ext_blocking_n == 1'b0)) begin
        ap_sub_ext_blocking_0 = 1'b1;
    end else begin
        ap_sub_ext_blocking_0 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_ap_int_blocking_n == 1'b0)) begin
        ap_sub_int_blocking_0 = 1'b1;
    end else begin
        ap_sub_int_blocking_0 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_ap_str_blocking_n == 1'b0)) begin
        ap_sub_str_blocking_0 = 1'b1;
    end else begin
        ap_sub_str_blocking_0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_ST_fsm_state149 == ap_CS_fsm)) begin
        ap_wait_0 = 1'b1;
    end else begin
        ap_wait_0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state77) | (1'b1 == ap_CS_fsm_state76) | (1'b1 == ap_CS_fsm_state75) | (1'b1 == ap_CS_fsm_state3))) begin
        hbm1_blk_n_AR = m_axi_hbm1_ARREADY;
    end else begin
        hbm1_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state150)) begin
        hbm1_blk_n_AW = m_axi_hbm1_AWREADY;
    end else begin
        hbm1_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state219)) begin
        hbm1_blk_n_B = m_axi_hbm1_BVALID;
    end else begin
        hbm1_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state147) | (1'b1 == ap_CS_fsm_state146) | (1'b1 == ap_CS_fsm_state145) | (1'b1 == ap_CS_fsm_state73))) begin
        hbm1_blk_n_R = m_axi_hbm1_RVALID;
    end else begin
        hbm1_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state151)) begin
        hbm1_blk_n_W = m_axi_hbm1_WREADY;
    end else begin
        hbm1_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((m_axi_hbm1_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state77))) begin
        m_axi_hbm1_ARADDR = hbm1_addr_3_reg_489;
    end else if (((m_axi_hbm1_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state76))) begin
        m_axi_hbm1_ARADDR = hbm1_addr_2_reg_502;
    end else if (((m_axi_hbm1_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state75))) begin
        m_axi_hbm1_ARADDR = sext_ln587_fu_336_p1;
    end else if (((m_axi_hbm1_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_hbm1_ARADDR = hbm1_addr_reg_467;
    end else if (((1'b1 == ap_CS_fsm_state148) | (1'b1 == ap_CS_fsm_state149))) begin
        m_axi_hbm1_ARADDR = grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_ARADDR;
    end else begin
        m_axi_hbm1_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state148) | (1'b1 == ap_CS_fsm_state149))) begin
        m_axi_hbm1_ARBURST = grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_ARBURST;
    end else begin
        m_axi_hbm1_ARBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state148) | (1'b1 == ap_CS_fsm_state149))) begin
        m_axi_hbm1_ARCACHE = grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_ARCACHE;
    end else begin
        m_axi_hbm1_ARCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state148) | (1'b1 == ap_CS_fsm_state149))) begin
        m_axi_hbm1_ARID = grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_ARID;
    end else begin
        m_axi_hbm1_ARID = 1'd0;
    end
end

always @ (*) begin
    if ((((m_axi_hbm1_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state77)) | ((m_axi_hbm1_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state76)) | ((m_axi_hbm1_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state75)) | ((m_axi_hbm1_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3)))) begin
        m_axi_hbm1_ARLEN = 32'd1;
    end else if (((1'b1 == ap_CS_fsm_state148) | (1'b1 == ap_CS_fsm_state149))) begin
        m_axi_hbm1_ARLEN = grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_ARLEN;
    end else begin
        m_axi_hbm1_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state148) | (1'b1 == ap_CS_fsm_state149))) begin
        m_axi_hbm1_ARLOCK = grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_ARLOCK;
    end else begin
        m_axi_hbm1_ARLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state148) | (1'b1 == ap_CS_fsm_state149))) begin
        m_axi_hbm1_ARPROT = grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_ARPROT;
    end else begin
        m_axi_hbm1_ARPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state148) | (1'b1 == ap_CS_fsm_state149))) begin
        m_axi_hbm1_ARQOS = grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_ARQOS;
    end else begin
        m_axi_hbm1_ARQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state148) | (1'b1 == ap_CS_fsm_state149))) begin
        m_axi_hbm1_ARREGION = grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_ARREGION;
    end else begin
        m_axi_hbm1_ARREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state148) | (1'b1 == ap_CS_fsm_state149))) begin
        m_axi_hbm1_ARSIZE = grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_ARSIZE;
    end else begin
        m_axi_hbm1_ARSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state148) | (1'b1 == ap_CS_fsm_state149))) begin
        m_axi_hbm1_ARUSER = grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_ARUSER;
    end else begin
        m_axi_hbm1_ARUSER = 1'd0;
    end
end

always @ (*) begin
    if ((((m_axi_hbm1_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state77)) | ((m_axi_hbm1_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state76)) | ((m_axi_hbm1_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state75)) | ((m_axi_hbm1_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3)))) begin
        m_axi_hbm1_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state148) | (1'b1 == ap_CS_fsm_state149))) begin
        m_axi_hbm1_ARVALID = grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_ARVALID;
    end else begin
        m_axi_hbm1_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_hbm1_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state150))) begin
        m_axi_hbm1_AWVALID = 1'b1;
    end else begin
        m_axi_hbm1_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_hbm1_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state219))) begin
        m_axi_hbm1_BREADY = 1'b1;
    end else begin
        m_axi_hbm1_BREADY = 1'b0;
    end
end

always @ (*) begin
    if ((((m_axi_hbm1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state147)) | ((m_axi_hbm1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state146)) | ((m_axi_hbm1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state145)) | ((m_axi_hbm1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state73)))) begin
        m_axi_hbm1_RREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state148) | (1'b1 == ap_CS_fsm_state149))) begin
        m_axi_hbm1_RREADY = grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_m_axi_hbm1_RREADY;
    end else begin
        m_axi_hbm1_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_hbm1_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state151))) begin
        m_axi_hbm1_WVALID = 1'b1;
    end else begin
        m_axi_hbm1_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln42_fu_229_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((m_axi_hbm1_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            ap_NS_fsm = ap_ST_fsm_state72;
        end
        ap_ST_fsm_state72 : begin
            ap_NS_fsm = ap_ST_fsm_state73;
        end
        ap_ST_fsm_state73 : begin
            if (((m_axi_hbm1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state73))) begin
                ap_NS_fsm = ap_ST_fsm_state74;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state73;
            end
        end
        ap_ST_fsm_state74 : begin
            ap_NS_fsm = ap_ST_fsm_state75;
        end
        ap_ST_fsm_state75 : begin
            if (((m_axi_hbm1_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state75))) begin
                ap_NS_fsm = ap_ST_fsm_state76;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state75;
            end
        end
        ap_ST_fsm_state76 : begin
            if (((m_axi_hbm1_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state76))) begin
                ap_NS_fsm = ap_ST_fsm_state77;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state76;
            end
        end
        ap_ST_fsm_state77 : begin
            if (((m_axi_hbm1_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state77))) begin
                ap_NS_fsm = ap_ST_fsm_state78;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state77;
            end
        end
        ap_ST_fsm_state78 : begin
            ap_NS_fsm = ap_ST_fsm_state79;
        end
        ap_ST_fsm_state79 : begin
            ap_NS_fsm = ap_ST_fsm_state80;
        end
        ap_ST_fsm_state80 : begin
            ap_NS_fsm = ap_ST_fsm_state81;
        end
        ap_ST_fsm_state81 : begin
            ap_NS_fsm = ap_ST_fsm_state82;
        end
        ap_ST_fsm_state82 : begin
            ap_NS_fsm = ap_ST_fsm_state83;
        end
        ap_ST_fsm_state83 : begin
            ap_NS_fsm = ap_ST_fsm_state84;
        end
        ap_ST_fsm_state84 : begin
            ap_NS_fsm = ap_ST_fsm_state85;
        end
        ap_ST_fsm_state85 : begin
            ap_NS_fsm = ap_ST_fsm_state86;
        end
        ap_ST_fsm_state86 : begin
            ap_NS_fsm = ap_ST_fsm_state87;
        end
        ap_ST_fsm_state87 : begin
            ap_NS_fsm = ap_ST_fsm_state88;
        end
        ap_ST_fsm_state88 : begin
            ap_NS_fsm = ap_ST_fsm_state89;
        end
        ap_ST_fsm_state89 : begin
            ap_NS_fsm = ap_ST_fsm_state90;
        end
        ap_ST_fsm_state90 : begin
            ap_NS_fsm = ap_ST_fsm_state91;
        end
        ap_ST_fsm_state91 : begin
            ap_NS_fsm = ap_ST_fsm_state92;
        end
        ap_ST_fsm_state92 : begin
            ap_NS_fsm = ap_ST_fsm_state93;
        end
        ap_ST_fsm_state93 : begin
            ap_NS_fsm = ap_ST_fsm_state94;
        end
        ap_ST_fsm_state94 : begin
            ap_NS_fsm = ap_ST_fsm_state95;
        end
        ap_ST_fsm_state95 : begin
            ap_NS_fsm = ap_ST_fsm_state96;
        end
        ap_ST_fsm_state96 : begin
            ap_NS_fsm = ap_ST_fsm_state97;
        end
        ap_ST_fsm_state97 : begin
            ap_NS_fsm = ap_ST_fsm_state98;
        end
        ap_ST_fsm_state98 : begin
            ap_NS_fsm = ap_ST_fsm_state99;
        end
        ap_ST_fsm_state99 : begin
            ap_NS_fsm = ap_ST_fsm_state100;
        end
        ap_ST_fsm_state100 : begin
            ap_NS_fsm = ap_ST_fsm_state101;
        end
        ap_ST_fsm_state101 : begin
            ap_NS_fsm = ap_ST_fsm_state102;
        end
        ap_ST_fsm_state102 : begin
            ap_NS_fsm = ap_ST_fsm_state103;
        end
        ap_ST_fsm_state103 : begin
            ap_NS_fsm = ap_ST_fsm_state104;
        end
        ap_ST_fsm_state104 : begin
            ap_NS_fsm = ap_ST_fsm_state105;
        end
        ap_ST_fsm_state105 : begin
            ap_NS_fsm = ap_ST_fsm_state106;
        end
        ap_ST_fsm_state106 : begin
            ap_NS_fsm = ap_ST_fsm_state107;
        end
        ap_ST_fsm_state107 : begin
            ap_NS_fsm = ap_ST_fsm_state108;
        end
        ap_ST_fsm_state108 : begin
            ap_NS_fsm = ap_ST_fsm_state109;
        end
        ap_ST_fsm_state109 : begin
            ap_NS_fsm = ap_ST_fsm_state110;
        end
        ap_ST_fsm_state110 : begin
            ap_NS_fsm = ap_ST_fsm_state111;
        end
        ap_ST_fsm_state111 : begin
            ap_NS_fsm = ap_ST_fsm_state112;
        end
        ap_ST_fsm_state112 : begin
            ap_NS_fsm = ap_ST_fsm_state113;
        end
        ap_ST_fsm_state113 : begin
            ap_NS_fsm = ap_ST_fsm_state114;
        end
        ap_ST_fsm_state114 : begin
            ap_NS_fsm = ap_ST_fsm_state115;
        end
        ap_ST_fsm_state115 : begin
            ap_NS_fsm = ap_ST_fsm_state116;
        end
        ap_ST_fsm_state116 : begin
            ap_NS_fsm = ap_ST_fsm_state117;
        end
        ap_ST_fsm_state117 : begin
            ap_NS_fsm = ap_ST_fsm_state118;
        end
        ap_ST_fsm_state118 : begin
            ap_NS_fsm = ap_ST_fsm_state119;
        end
        ap_ST_fsm_state119 : begin
            ap_NS_fsm = ap_ST_fsm_state120;
        end
        ap_ST_fsm_state120 : begin
            ap_NS_fsm = ap_ST_fsm_state121;
        end
        ap_ST_fsm_state121 : begin
            ap_NS_fsm = ap_ST_fsm_state122;
        end
        ap_ST_fsm_state122 : begin
            ap_NS_fsm = ap_ST_fsm_state123;
        end
        ap_ST_fsm_state123 : begin
            ap_NS_fsm = ap_ST_fsm_state124;
        end
        ap_ST_fsm_state124 : begin
            ap_NS_fsm = ap_ST_fsm_state125;
        end
        ap_ST_fsm_state125 : begin
            ap_NS_fsm = ap_ST_fsm_state126;
        end
        ap_ST_fsm_state126 : begin
            ap_NS_fsm = ap_ST_fsm_state127;
        end
        ap_ST_fsm_state127 : begin
            ap_NS_fsm = ap_ST_fsm_state128;
        end
        ap_ST_fsm_state128 : begin
            ap_NS_fsm = ap_ST_fsm_state129;
        end
        ap_ST_fsm_state129 : begin
            ap_NS_fsm = ap_ST_fsm_state130;
        end
        ap_ST_fsm_state130 : begin
            ap_NS_fsm = ap_ST_fsm_state131;
        end
        ap_ST_fsm_state131 : begin
            ap_NS_fsm = ap_ST_fsm_state132;
        end
        ap_ST_fsm_state132 : begin
            ap_NS_fsm = ap_ST_fsm_state133;
        end
        ap_ST_fsm_state133 : begin
            ap_NS_fsm = ap_ST_fsm_state134;
        end
        ap_ST_fsm_state134 : begin
            ap_NS_fsm = ap_ST_fsm_state135;
        end
        ap_ST_fsm_state135 : begin
            ap_NS_fsm = ap_ST_fsm_state136;
        end
        ap_ST_fsm_state136 : begin
            ap_NS_fsm = ap_ST_fsm_state137;
        end
        ap_ST_fsm_state137 : begin
            ap_NS_fsm = ap_ST_fsm_state138;
        end
        ap_ST_fsm_state138 : begin
            ap_NS_fsm = ap_ST_fsm_state139;
        end
        ap_ST_fsm_state139 : begin
            ap_NS_fsm = ap_ST_fsm_state140;
        end
        ap_ST_fsm_state140 : begin
            ap_NS_fsm = ap_ST_fsm_state141;
        end
        ap_ST_fsm_state141 : begin
            ap_NS_fsm = ap_ST_fsm_state142;
        end
        ap_ST_fsm_state142 : begin
            ap_NS_fsm = ap_ST_fsm_state143;
        end
        ap_ST_fsm_state143 : begin
            ap_NS_fsm = ap_ST_fsm_state144;
        end
        ap_ST_fsm_state144 : begin
            ap_NS_fsm = ap_ST_fsm_state145;
        end
        ap_ST_fsm_state145 : begin
            if (((m_axi_hbm1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state145))) begin
                ap_NS_fsm = ap_ST_fsm_state146;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state145;
            end
        end
        ap_ST_fsm_state146 : begin
            if (((m_axi_hbm1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state146))) begin
                ap_NS_fsm = ap_ST_fsm_state147;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state146;
            end
        end
        ap_ST_fsm_state147 : begin
            if (((m_axi_hbm1_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state147))) begin
                ap_NS_fsm = ap_ST_fsm_state148;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state147;
            end
        end
        ap_ST_fsm_state148 : begin
            ap_NS_fsm = ap_ST_fsm_state149;
        end
        ap_ST_fsm_state149 : begin
            if (((grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state149))) begin
                ap_NS_fsm = ap_ST_fsm_state150;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state149;
            end
        end
        ap_ST_fsm_state150 : begin
            if (((m_axi_hbm1_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state150))) begin
                ap_NS_fsm = ap_ST_fsm_state151;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state150;
            end
        end
        ap_ST_fsm_state151 : begin
            if (((m_axi_hbm1_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state151))) begin
                ap_NS_fsm = ap_ST_fsm_state152;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state151;
            end
        end
        ap_ST_fsm_state152 : begin
            ap_NS_fsm = ap_ST_fsm_state153;
        end
        ap_ST_fsm_state153 : begin
            ap_NS_fsm = ap_ST_fsm_state154;
        end
        ap_ST_fsm_state154 : begin
            ap_NS_fsm = ap_ST_fsm_state155;
        end
        ap_ST_fsm_state155 : begin
            ap_NS_fsm = ap_ST_fsm_state156;
        end
        ap_ST_fsm_state156 : begin
            ap_NS_fsm = ap_ST_fsm_state157;
        end
        ap_ST_fsm_state157 : begin
            ap_NS_fsm = ap_ST_fsm_state158;
        end
        ap_ST_fsm_state158 : begin
            ap_NS_fsm = ap_ST_fsm_state159;
        end
        ap_ST_fsm_state159 : begin
            ap_NS_fsm = ap_ST_fsm_state160;
        end
        ap_ST_fsm_state160 : begin
            ap_NS_fsm = ap_ST_fsm_state161;
        end
        ap_ST_fsm_state161 : begin
            ap_NS_fsm = ap_ST_fsm_state162;
        end
        ap_ST_fsm_state162 : begin
            ap_NS_fsm = ap_ST_fsm_state163;
        end
        ap_ST_fsm_state163 : begin
            ap_NS_fsm = ap_ST_fsm_state164;
        end
        ap_ST_fsm_state164 : begin
            ap_NS_fsm = ap_ST_fsm_state165;
        end
        ap_ST_fsm_state165 : begin
            ap_NS_fsm = ap_ST_fsm_state166;
        end
        ap_ST_fsm_state166 : begin
            ap_NS_fsm = ap_ST_fsm_state167;
        end
        ap_ST_fsm_state167 : begin
            ap_NS_fsm = ap_ST_fsm_state168;
        end
        ap_ST_fsm_state168 : begin
            ap_NS_fsm = ap_ST_fsm_state169;
        end
        ap_ST_fsm_state169 : begin
            ap_NS_fsm = ap_ST_fsm_state170;
        end
        ap_ST_fsm_state170 : begin
            ap_NS_fsm = ap_ST_fsm_state171;
        end
        ap_ST_fsm_state171 : begin
            ap_NS_fsm = ap_ST_fsm_state172;
        end
        ap_ST_fsm_state172 : begin
            ap_NS_fsm = ap_ST_fsm_state173;
        end
        ap_ST_fsm_state173 : begin
            ap_NS_fsm = ap_ST_fsm_state174;
        end
        ap_ST_fsm_state174 : begin
            ap_NS_fsm = ap_ST_fsm_state175;
        end
        ap_ST_fsm_state175 : begin
            ap_NS_fsm = ap_ST_fsm_state176;
        end
        ap_ST_fsm_state176 : begin
            ap_NS_fsm = ap_ST_fsm_state177;
        end
        ap_ST_fsm_state177 : begin
            ap_NS_fsm = ap_ST_fsm_state178;
        end
        ap_ST_fsm_state178 : begin
            ap_NS_fsm = ap_ST_fsm_state179;
        end
        ap_ST_fsm_state179 : begin
            ap_NS_fsm = ap_ST_fsm_state180;
        end
        ap_ST_fsm_state180 : begin
            ap_NS_fsm = ap_ST_fsm_state181;
        end
        ap_ST_fsm_state181 : begin
            ap_NS_fsm = ap_ST_fsm_state182;
        end
        ap_ST_fsm_state182 : begin
            ap_NS_fsm = ap_ST_fsm_state183;
        end
        ap_ST_fsm_state183 : begin
            ap_NS_fsm = ap_ST_fsm_state184;
        end
        ap_ST_fsm_state184 : begin
            ap_NS_fsm = ap_ST_fsm_state185;
        end
        ap_ST_fsm_state185 : begin
            ap_NS_fsm = ap_ST_fsm_state186;
        end
        ap_ST_fsm_state186 : begin
            ap_NS_fsm = ap_ST_fsm_state187;
        end
        ap_ST_fsm_state187 : begin
            ap_NS_fsm = ap_ST_fsm_state188;
        end
        ap_ST_fsm_state188 : begin
            ap_NS_fsm = ap_ST_fsm_state189;
        end
        ap_ST_fsm_state189 : begin
            ap_NS_fsm = ap_ST_fsm_state190;
        end
        ap_ST_fsm_state190 : begin
            ap_NS_fsm = ap_ST_fsm_state191;
        end
        ap_ST_fsm_state191 : begin
            ap_NS_fsm = ap_ST_fsm_state192;
        end
        ap_ST_fsm_state192 : begin
            ap_NS_fsm = ap_ST_fsm_state193;
        end
        ap_ST_fsm_state193 : begin
            ap_NS_fsm = ap_ST_fsm_state194;
        end
        ap_ST_fsm_state194 : begin
            ap_NS_fsm = ap_ST_fsm_state195;
        end
        ap_ST_fsm_state195 : begin
            ap_NS_fsm = ap_ST_fsm_state196;
        end
        ap_ST_fsm_state196 : begin
            ap_NS_fsm = ap_ST_fsm_state197;
        end
        ap_ST_fsm_state197 : begin
            ap_NS_fsm = ap_ST_fsm_state198;
        end
        ap_ST_fsm_state198 : begin
            ap_NS_fsm = ap_ST_fsm_state199;
        end
        ap_ST_fsm_state199 : begin
            ap_NS_fsm = ap_ST_fsm_state200;
        end
        ap_ST_fsm_state200 : begin
            ap_NS_fsm = ap_ST_fsm_state201;
        end
        ap_ST_fsm_state201 : begin
            ap_NS_fsm = ap_ST_fsm_state202;
        end
        ap_ST_fsm_state202 : begin
            ap_NS_fsm = ap_ST_fsm_state203;
        end
        ap_ST_fsm_state203 : begin
            ap_NS_fsm = ap_ST_fsm_state204;
        end
        ap_ST_fsm_state204 : begin
            ap_NS_fsm = ap_ST_fsm_state205;
        end
        ap_ST_fsm_state205 : begin
            ap_NS_fsm = ap_ST_fsm_state206;
        end
        ap_ST_fsm_state206 : begin
            ap_NS_fsm = ap_ST_fsm_state207;
        end
        ap_ST_fsm_state207 : begin
            ap_NS_fsm = ap_ST_fsm_state208;
        end
        ap_ST_fsm_state208 : begin
            ap_NS_fsm = ap_ST_fsm_state209;
        end
        ap_ST_fsm_state209 : begin
            ap_NS_fsm = ap_ST_fsm_state210;
        end
        ap_ST_fsm_state210 : begin
            ap_NS_fsm = ap_ST_fsm_state211;
        end
        ap_ST_fsm_state211 : begin
            ap_NS_fsm = ap_ST_fsm_state212;
        end
        ap_ST_fsm_state212 : begin
            ap_NS_fsm = ap_ST_fsm_state213;
        end
        ap_ST_fsm_state213 : begin
            ap_NS_fsm = ap_ST_fsm_state214;
        end
        ap_ST_fsm_state214 : begin
            ap_NS_fsm = ap_ST_fsm_state215;
        end
        ap_ST_fsm_state215 : begin
            ap_NS_fsm = ap_ST_fsm_state216;
        end
        ap_ST_fsm_state216 : begin
            ap_NS_fsm = ap_ST_fsm_state217;
        end
        ap_ST_fsm_state217 : begin
            ap_NS_fsm = ap_ST_fsm_state218;
        end
        ap_ST_fsm_state218 : begin
            ap_NS_fsm = ap_ST_fsm_state219;
        end
        ap_ST_fsm_state219 : begin
            if (((m_axi_hbm1_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state219))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state219;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln21_fu_376_p2 = (zext_ln21_fu_372_p1 + vh_index);

assign add_ln42_fu_234_p2 = (i_fu_82 + 32'd1);

assign add_ln587_43_fu_285_p2 = (zext_ln587_fu_281_p1 + vh_offset);

assign add_ln587_44_fu_349_p2 = ($signed(sext_ln587_45_fu_339_p1) + $signed(63'd1));

assign add_ln587_45_fu_311_p2 = (zext_ln587_15_fu_307_p1 + V_value);

assign add_ln587_fu_244_p2 = ($signed(sext_ln42_reg_459) + $signed(zext_ln42_fu_240_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state145 = ap_CS_fsm[32'd144];

assign ap_CS_fsm_state146 = ap_CS_fsm[32'd145];

assign ap_CS_fsm_state147 = ap_CS_fsm[32'd146];

assign ap_CS_fsm_state148 = ap_CS_fsm[32'd147];

assign ap_CS_fsm_state149 = ap_CS_fsm[32'd148];

assign ap_CS_fsm_state150 = ap_CS_fsm[32'd149];

assign ap_CS_fsm_state151 = ap_CS_fsm[32'd150];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state219 = ap_CS_fsm[32'd218];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state73 = ap_CS_fsm[32'd72];

assign ap_CS_fsm_state74 = ap_CS_fsm[32'd73];

assign ap_CS_fsm_state75 = ap_CS_fsm[32'd74];

assign ap_CS_fsm_state76 = ap_CS_fsm[32'd75];

assign ap_CS_fsm_state77 = ap_CS_fsm[32'd76];

assign ap_NS_fsm_state148 = ap_NS_fsm[32'd147];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign ap_ext_blocking_cur_n = (hbm1_blk_n_W & hbm1_blk_n_R & hbm1_blk_n_B & hbm1_blk_n_AW & hbm1_blk_n_AR);

assign ap_ext_blocking_n = (ap_ext_blocking_sub_n & ap_ext_blocking_cur_n);

assign ap_int_blocking_n = (ap_int_blocking_sub_n & 1'b1);

assign ap_str_blocking_n = (ap_str_blocking_sub_n & 1'b1);

assign grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_ap_start = grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_ap_start_reg;

assign icmp_ln25_fu_399_p2 = ((origin_value_44_fu_394_p2 < k) ? 1'b1 : 1'b0);

assign icmp_ln42_fu_229_p2 = ((i_fu_82 == to_process_vertex_count) ? 1'b1 : 1'b0);

assign m_axi_hbm1_AWADDR = hbm1_addr_3_reg_489;

assign m_axi_hbm1_AWBURST = 2'd0;

assign m_axi_hbm1_AWCACHE = 4'd0;

assign m_axi_hbm1_AWID = 1'd0;

assign m_axi_hbm1_AWLEN = 32'd1;

assign m_axi_hbm1_AWLOCK = 2'd0;

assign m_axi_hbm1_AWPROT = 3'd0;

assign m_axi_hbm1_AWQOS = 4'd0;

assign m_axi_hbm1_AWREGION = 4'd0;

assign m_axi_hbm1_AWSIZE = 3'd0;

assign m_axi_hbm1_AWUSER = 1'd0;

assign m_axi_hbm1_WDATA = origin_value_45_reg_529;

assign m_axi_hbm1_WID = 1'd0;

assign m_axi_hbm1_WLAST = 1'b0;

assign m_axi_hbm1_WSTRB = 4'd15;

assign m_axi_hbm1_WUSER = 1'd0;

assign origin_value_43_fu_201_p2 = ($signed(k) + $signed(32'd4294967295));

assign origin_value_44_fu_394_p2 = (origin_value_reg_524 - grp_kernel_kcore_h2v_pe_1_Pipeline_VITIS_LOOP_21_1_fu_190_h_active_count_out);

assign origin_value_45_fu_404_p3 = ((icmp_ln25_fu_399_p2[0:0] == 1'b1) ? origin_value_43_reg_454 : origin_value_44_fu_394_p2);

assign sext_ln42_fu_217_p1 = $signed(trunc_ln_fu_207_p4);

assign sext_ln587_15_fu_326_p1 = $signed(trunc_ln587_s_fu_316_p4);

assign sext_ln587_44_fu_249_p1 = $signed(add_ln587_fu_244_p2);

assign sext_ln587_45_fu_339_p1 = trunc_ln23_reg_483;

assign sext_ln587_46_fu_355_p1 = $signed(add_ln587_44_fu_349_p2);

assign sext_ln587_fu_336_p1 = trunc_ln23_reg_483;

assign shl_ln10_fu_365_p3 = {{begin_reg_508}, {2'd0}};

assign shl_ln587_s_fu_300_p3 = {{hbm1_addr_read_reg_473}, {2'd0}};

assign shl_ln_fu_274_p3 = {{tmp_reg_478}, {2'd0}};

assign trunc_ln587_s_fu_316_p4 = {{add_ln587_45_fu_311_p2[63:2]}};

assign trunc_ln_fu_207_p4 = {{to_process_vertex[63:2]}};

assign zext_ln21_fu_372_p1 = shl_ln10_fu_365_p3;

assign zext_ln42_fu_240_p1 = i_fu_82;

assign zext_ln587_15_fu_307_p1 = shl_ln587_s_fu_300_p3;

assign zext_ln587_fu_281_p1 = shl_ln_fu_274_p3;

endmodule //kernel_kcore_h2v_kernel_kcore_h2v_pe_1
